<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Athens State University</h1>
         <h2>Athens, AL</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>300 North Beaty Street </p>
                  <p>Athens, AL 35611 </p>
                  <p>www.athens.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>300 North Beaty Street </p>
                  <p>Athens, AL 35611 </p>
                  <p>(256) 233-8220 </p>
                  <p>Fax : (256) 233-6565 </p>
                  <p>admissions@athens.edu </p>
                  <p>Contact : Necedah Henderson </p>
                  <p>Coordinator of Admissions </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Medium </p>
                  <p>Public </p>
                  <p>liberal arts college </p>
                  <p>teachers college/college of education </p>
                  <p>Upper division school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>College Board Code: 0706 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Total undergraduates : 3,415 </p>
                  <p>In-State Tuition : $5,760.00 </p>
                  <p>Out-of-State Tuition : $10,770.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Certificate </p>
                  <p>Bachelor's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Large Town (10-50k) </p>
                  <p>Suburban </p>
                  <p>Commuter campus </p>
         </td>
         
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   --</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   --</p>
                  <p>SAT subject score report due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   --</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   Jul 11</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   16 to 1</p>
                  <p>Degree's Offered in :   Certificate, Bachelor's degrees</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Education : 34.0%<br/>Business/Marketing : 31.0%<br/>Computer and Information Sciences : 6.0%<br/>Interdisciplinary Studies : 6.0%<br/>Liberal Arts : 6.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biology/Biological Sciences, General B<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Business Administration and Management, General B<br/>Human Resources Management/Personnel Administration, General B<br/>Information Resources Management/CIO Training B<br/>Purchasing, Procurement/Acquisitions and Contracts Management C<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer and Information Sciences, General B<br/></p>
                  <p><b>Education</b><br/>  Biology Teacher Education B<br/>Chemistry Teacher Education B<br/>Early Childhood Education and Teaching B<br/>Education, General B<br/>Elementary Education and Teaching B<br/>English/Language Arts Teacher Education B<br/>History Teacher Education B<br/>Junior High/Intermediate/Middle School Education and Teaching B<br/>Mathematics Teacher Education B<br/>Physical Education Teaching and Coaching B<br/>Physics Teacher Education B<br/>Science Teacher Education/General Science Teacher Education B<br/>Secondary Education and Teaching B<br/>Social Science Teacher Education B<br/>Social Studies Teacher Education B<br/>Special Education and Teaching, General B<br/>Trade and Industrial Teacher Education B<br/></p>
                  <p><b>Engineering Technologies/Technicians</b><br/>  Instrumentation Technology/Technician B<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  English Language and Literature, General B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Liberal Arts and Sciences/Liberal Studies B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/></p>
                  <p><b>Multi & Interdisciplinary Studies</b><br/>  Behavioral Sciences B<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Religion/Religious Studies B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Chemistry, General B<br/>Physics, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B<br/></p>
                  <p><b>Security & Protective Services</b><br/>  Criminal Justice/Safety Studies B<br/></p>
                  <p><b>Social Sciences</b><br/>  Political Science and Government, General B<br/>Sociology B<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Art/Art Studies, General B<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Cooperative Education </p>
                  <p>Double Major </p>
                  <p>Dual Enrollment of High School Students </p>
                  <p>Independent Study </p>
                  <p>Teacher Certification </p>
                  <p>Honors Program </p>
                  <p>Internships </p>
                  <p>Liberal Arts/Career Combination </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Study Abroad </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Extensive evening or early morning classes </p>
                  <p>Saturday Classes </p>
                  <p>Distance Learning </p>
                  <p>Weekend College </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>341 Public computers, available in: Computer Center, Libraries, Student Center </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Medium-sized</p>
                  <p>Geographic Location :   14 miles from Decatur, 24 miles from Huntsville.</p>
                  <p>Large Town </p>
                  <p>Suburban </p>
                  <p>Commuter Campus </p>
                  <p>Total undergraduates :   3,415</p>
                  <p>First-time degree-seeking freshmen :   --</p>
                  <p>Degree-seeking undergrads :   3,268</p>
                  <p>Graduate enrollment :   --</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   31</p>
                  <p>Full time students average age :   27</p>
                  <p>In state students :   96.0%</p>
                  <p>Out of  state students :   4.0%</p>
                  <p>Part Time students :   53.0%</p>
                  <p>Percentage of males :   34.0%</p>
                  <p>Percentage of females :   66.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Two or more races :   1.0%</p>
                  <p>American Indian/Alaskan Native :   2.0%</p>
                  <p>Black African American :   12.0%</p>
                  <p>Hispanic/Latino :   2.0%</p>
                  <p>Race Ethnicity Unknown :   3.0%</p>
                  <p>White :   78.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>Student Newspaper :   The Athenian</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Career counseling </p>
                  <p>Employment services for undergraduates </p>
                  <p>Financial aid counseling </p>
                  <p>Minority students services </p>
                  <p>Placement services for graduates </p>
                  <p>Veteran's counselor </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Services and/or facilities for speech or communications disorders </p>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Wheelchair Accessibility </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
            </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $30.00</p>
                  <p>Application fee notes:   Paper/Online</p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Open admissions for junior and senior level college students only. </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>Offers placement into higher-level courses for AP Exams : Yes </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Freshman College Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Humanities</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Mathematics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Natural Science</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Sciences and History</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   32.0%</p>
                  <p>% of loans / jobs :   68.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Renee Stanford</p>
                  <p>Financial aid office phone :  (256) 233-8170</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $167.00</p>
                  <p>Cost per credit hour (out-of-state):  $334.00</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Job Skills </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
                  <p>Art </p>
                  <p>Athletics </p>
                  <p>Leadership </p>
                  <p>Minority Status </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>For part-time students </p>
                  <p>Weekends </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $5,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $5,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $5,760.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $10,770.00</p>
                              </td>
                              <td class=col4>
                                 <p> $10,770.00</p>
                              </td>
                              <td class=col4>
                                 <p> $10,770.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room only:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $800.00</p>
                              </td>
                              <td class=col4>
                                 <p> $800.00</p>
                              </td>
                              <td class=col4>
                                 <p> $800.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> $3,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> $3,000.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $6,560.00</p>
                              </td>
                              <td class=col4>
                                 <p> $9,560.00</p>
                              </td>
                              <td class=col4>
                                 <p> $9,560.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $11,570.00</p>
                              </td>
                              <td class=col4>
                                 <p> $14,570.00</p>
                              </td>
                              <td class=col4>
                                 <p> $14,570.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  64</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  1</p>
                  <p>Maximum credits/courses from a 2-year institution:  --</p>
                  <p>Maximum credits/courses from a 4-year institution:  --</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  33</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>College Transcript(s) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  690</p>
                  <p>Transfers admitted percentage:  84.0%</p>
                  <p>Transfers admitted:  582</p>
                  <p>Transfers enrolled percentage:  65.0%</p>
                  <p>Transfers enrolled:  454</p>
                  <p>Students who applied for transfer from 2 year schools:  81.0%</p>
                  <p>Students who applied for transfer from 4 year schools:  19.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>Junior </p>
                  <p>Senior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>-- </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  Jul 11</p>
                  <p>Application fee:  $30.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $10,770.00</p>
                  <p>Room & Board(on-campus):  --</p>
                  <p>Room & Board(off-campus):  --</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $334.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>International students eligible for non-need based aid </p>
                  <p>Non-resident aliens must submit the following financial aid forms: </p>
                  <p>Foreign Student Certification of Finances </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  --</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>