<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Amberton University</h1>
         <h2>Garland, TX</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>1700 Eastgate Drive </p>
                  <p>Garland, TX 75041 </p>
                  <p>www.amberton.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>1700 Eastgate Drive </p>
                  <p>Garland, TX 75041-5595 </p>
                  <p>(972) 279-6511 </p>
                  <p>Fax : (972) 279-9773 </p>
                  <p>advisor@amberton.edu </p>
                  <p>Contact : Don Hebbard </p>
                  <p>Academic Dean </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Small </p>
                  <p>Private </p>
                  <p>university </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>Nondenominational </p>
                  <p>College Board Code: 6140 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Total undergraduates : 269 </p>
                  <p>Average financial aid package : $0.00 </p>
                  <p>In-State Tuition : $7,260.00 </p>
                  <p>Out-of-State Tuition : $7,260.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p> </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Bachelor's </p>
                  <p>Master's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small City (50-250k) </p>
                  <p>Suburban </p>
                  <p>Commuter campus </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Characteristics</h2>

            <div class="subTabSeperator"></div>
                  <p>Upper level and graduate institution designed for adult students. Must have previous college and be over 21 years old to attend. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   --</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   --</p>
                  <p>SAT subject score report due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   --</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   </p>
                  <p>Degree's Offered in :   Bachelor's, Master's degrees</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Business/Marketing : 90.0%<br/>Liberal Arts : 10.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Business Administration and Management, General B M<br/>Business/Commerce, General B M<br/>Human Resources Management/Personnel Administration, General M<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Liberal Arts and Sciences/Liberal Studies B<br/></p>
                  <p><b>Psychology</b><br/>  Counseling Psychology M<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Independent Study </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Extensive evening or early morning classes </p>
                  <p>Saturday Classes </p>
                  <p>Distance Learning </p>
                  <p>Weekend College </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>25 Public computers, available in: Computer Center, Libraries </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Small</p>
                  <p>Geographic Location :   12 miles from downtown Dallas.</p>
                  <p>Small City </p>
                  <p>Suburban </p>
                  <p>Commuter Campus </p>
                  <p>Total undergraduates :   269</p>
                  <p>First-time degree-seeking freshmen :   --</p>
                  <p>Degree-seeking undergrads :   269</p>
                  <p>Graduate enrollment :   1,109</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   37</p>
                  <p>Full time students average age :   37</p>
                  <p>Part Time students :   46.0%</p>
                  <p>Percentage of males :   41.0%</p>
                  <p>Percentage of females :   59.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Black African American :   30.0%</p>
                  <p>Asian :   9.0%</p>
                  <p>Hispanic/Latino :   8.0%</p>
                  <p>Race Ethnicity Unknown :   4.0%</p>
                  <p>White :   49.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Car is not allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Career counseling </p>
                  <p>Personal counseling </p>
                  <p>Placement services for graduates </p>
                  <p>Adult (re-entering) student services/programs </p>
                  <p>Veteran's counselor </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Wheelchair Accessibility </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
            </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $0.00</p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Applicants must be at least 21 years of age, have completed college work in a U.S. institution, and be a U.S. citizen. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>Average 1st year financial aid package :   $0.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Brent Bradshaw</p>
                  <p>Financial aid office phone :  (972) 279-6511</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $242.00</p>
                  <p>Cost per credit hour (out-of-state):  --</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Deferred payment </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,260.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room only:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $500.00</p>
                              </td>
                              <td class=col4>
                                 <p> $500.00</p>
                              </td>
                              <td class=col4>
                                 <p> $500.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,760.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  30</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  --</p>
                  <p>Maximum credits/courses from a 4-year institution:  --</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  30</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>Statement of good standing from Prior Institution(s) </p>
                  <p>College Transcript(s) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Students who applied for transfer from 2 year schools:  50.0%</p>
                  <p>Students who applied for transfer from 4 year schools:  50.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Winter </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>Junior </p>
                  <p>Senior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring OUT of this school</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer advisor </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer candidates must have completed 30 hours of course work with at least 2.0 GPA at regionally accredited institution. Must be at least 21. Interview required for international applicants. Must have completed some college. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Application fee:  $100.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $7,260.00</p>
                  <p>Room & Board(on-campus):  --</p>
                  <p>Room & Board(off-campus):  --</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $242.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  --</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>