<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Colorado Mountain College</h1>
         <h2>Glenwood Springs, CO</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>802 Grand Avenue </p>
                  <p>Glenwood Springs, CO 81601 </p>
                  <p>www.coloradomtn.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>802 Grand Avenue </p>
                  <p>Glenwood Springs, CO 81601 </p>
                  <p>(970) 945-8691 </p>
                  <p>joinus@coloradomtn.edu </p>
                  <p>Contact : Bill Sommers </p>
                  <p>Assistant Vice President, Enrollment Services </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Medium </p>
                  <p>Public </p>
                  <p>community college </p>
                  <p>liberal arts college </p>
                  <p>2-year school </p>
                  <p>Coed </p>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>Regionally Accredited </p>
                  <p>College Board Code: 4112 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Total undergraduates : 5,847 </p>
                  <p>In-State Tuition : $1,980.00 </p>
                  <p>Out-of-State Tuition : $9,270.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Certificate </p>
                  <p>Diploma </p>
                  <p>Associate </p>
                  <p>Bachelor's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small Town (2,500-10k) </p>
                  <p>Rural </p>
                  <p>Residential campus </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Characteristics</h2>

            <div class="subTabSeperator"></div>
                  <p>Composed of 12 campuses. 3 campuses have residential facilities: Alpine Campus in Steamboat Springs; Spring Valley Campus in Glenwood Springs and Timberline Campus in Leadville. Commuter campuses located in Aspen, Breckenridge, Buena Vista, Carbondale, Dillion, Edwards, Glenwood Springs and Rifle. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   --</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   --</p>
                  <p>SAT subject score report due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Mar 31</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   May 1</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Degree's Offered in :   Certificate, Diploma, Associate, Bachelor's degrees</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>Regionally Accredited </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Associates</b><br/>  Liberal Arts : 65.0%<br/>Health Professions : 14.0%<br/>Business/Marketing : 8.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Agriculture & Related Sciences</b><br/>  Animal Health A<br/>Farm/Farm and Ranch Management C<br/>Food Science A<br/>Food Technology and Processing A<br/>Soil Science and Agronomy, General A<br/></p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biology/Biological Sciences, General A<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting A C<br/>Accounting Technology/Technician and Bookkeeping A C<br/>Business Administration and Management, General A B C<br/>Business/Commerce, General A C<br/>Hospitality Administration/Management, General A C<br/>Hotel/Motel Administration/Management A<br/>Management Information Systems, General A<br/>Real Estate A C<br/>Resort Management A C<br/>Tourism and Travel Services Management A C<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Photojournalism A<br/></p>
                  <p><b>Communications Technologies & Support Services</b><br/>  Animation, Interactive Technology, Video Graphics and  Special  Effects A<br/>Graphic Communications, General A<br/>Graphic and Printing Equipment Operator, General Production A<br/>Photographic  and Film/ Video Technology/Technician and Assistant A<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer Graphics A<br/>Computer Programming, Specific Applications A<br/>Computer Programming/Programmer, General A<br/>Computer Systems Networking and Telecommunications A<br/>Computer and Information Sciences, General A<br/>Data Processing and Data Processing Technology/Technician C<br/>Information Technology A<br/>Web Page, Digital/Multimedia and Information Resources Design C<br/></p>
                  <p><b>Education</b><br/>  Bilingual and Multilingual Education A<br/>Early Childhood Education and Teaching A C<br/>Education, General A<br/></p>
                  <p><b>Engineering Technologies/Technicians</b><br/>  Energy Management and Systems Technology/Technician C<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  English Language and Literature, General A<br/>Rhetoric and Composition A<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Emergency Care Attendant (EMT Ambulance) C<br/>Emergency Medical Technology/Technician (EMT Paramedic) A C<br/>Health Services/Allied Health/Health Sciences, General C<br/>Licensed Practical /Vocational Nurse Training (LPN, LVN, Cert, Dipl, AAS) C<br/>Medical Office Assistant/Specialist A C<br/>Nurse/Nursing Assistant/Aide and Patient Care Assistant C<br/>Nursing - Registered Nurse Training (RN, ASN, BSN, MSN) A<br/>Pre-Nursing Studies A<br/>Veterinary/Animal Health Technology/Technician and Veterinary Assistant A<br/></p>
                  <p><b>Legal Professions & Studies</b><br/>  Legal Assistant/Paralegal A C<br/>Pre-Law Studies A<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  General Studies A<br/>Liberal Arts and Sciences/Liberal Studies A<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General A<br/></p>
                  <p><b>Mechanic & Repair Technologies</b><br/>  Automobile/Automotive Mechanics Technology/Technician C<br/></p>
                  <p><b>Multi & Interdisciplinary Studies</b><br/>  Accounting and Computer Science A<br/>Biological and Physical Sciences A<br/>Historic Preservation and Conservation A<br/>Natural Sciences A<br/>Science, Technology and Society A<br/>Sustainability Studies B<br/></p>
                  <p><b>Natural Resources & Conservation</b><br/>  Forestry Technology/Technician C<br/>Forestry, General A<br/>Natural Resources Management and Policy A<br/>Natural Resources/Conservation, General A<br/></p>
                  <p><b>Parks, Recreation & Fitness Studies</b><br/>  Parks, Recreation and Leisure Facilities Management A<br/>Parks, Recreation and Leisure Studies A<br/></p>
                  <p><b>Personal & Culinary Services</b><br/>  Baking and Pastry Arts/Baker/Pastry Chef C<br/>Cooking and Related Culinary Arts, General A<br/>Culinary Arts/Chef Training A<br/>Food Preparation/Professional Cooking/Kitchen Assistant A<br/>Personal And Culinary Services, General A<br/>Restaurant, Culinary, and Catering Management/Manager A<br/></p>
                  <p><b>Physical Sciences</b><br/>  Astronomy C<br/>Chemistry, General A<br/>Geology/Earth Science, General A<br/>Physical Sciences C<br/></p>
                  <p><b>Precision Production</b><br/>  Welding Technology/Welder C<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General C<br/></p>
                  <p><b>Security & Protective Services</b><br/>  Criminal Justice/Police Science C<br/>Criminal Justice/Safety Studies A<br/>Fire Protection and Safety Technology/Technician C<br/>Fire Science/Firefighting A<br/>Fire Services Administration C<br/></p>
                  <p><b>Social Sciences</b><br/>  Social Sciences, General A<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Acting C<br/>Art/Art Studies, General A<br/>Commercial Photography A<br/>Commercial and Advertising Art A C<br/>Design and Visual Communications, General A<br/>Digital art C<br/>Drama and Dramatics/Theater Arts, General A<br/>Graphic Design A<br/>Photography A C<br/>Theatre/Theatre Arts Management C<br/>Visual and Performing Arts, General A<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Dual Enrollment of High School Students </p>
                  <p>Independent Study </p>
                  <p>Internships </p>
                  <p>Liberal Arts/Career Combination </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Study Abroad </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Extensive evening or early morning classes </p>
                  <p>Saturday Classes </p>
                  <p>Distance Learning </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>30 Public computers, available in: Computer Center, Dorms, Libraries, Student Center </p>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Wireless network available </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Medium-sized</p>
                  <p>Unique Facilities :   outdoor education center, farm for veterinarian technician program, climbing wall, ice wall, community theater</p>
                  <p>Geographic Location :   160 miles from Denver.</p>
                  <p>Small Town </p>
                  <p>Rural </p>
                  <p>Residential Campus </p>
                  <p>Total undergraduates :   5,847</p>
                  <p>First-time degree-seeking freshmen :   --</p>
                  <p>Degree-seeking undergrads :   3,467</p>
                  <p>Graduate enrollment :   --</p>
         </td>
         
         
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Asian :   1.0%</p>
                  <p>Race Ethnicity Unknown :   20.0%</p>
                  <p>White :   76.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>Other Activities & Organizations :   All students living on-campus must follow housing policies.</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Coed Housing </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit :   $300.00</p>
                  <p>Housing deposit is refundable in full if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   Eagles</p>
                  <p>Sport Member :   NJCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Scholarship </p>
                  <p>Club </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Placement services for graduates </p>
                  <p>Adult (re-entering) student services/programs </p>
                  <p>Veteran's counselor </p>
                  <p>Career counseling </p>
                  <p>Employment services for undergraduates </p>
                  <p>Personal counseling </p>
                  <p>Financial aid counseling </p>
                  <p>Health services </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for speech or communications disorders </p>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Wheelchair Accessibility </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Reduced course load </p>
                  <p>Remedial instruction </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ice Hockey</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Rugby</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Skiing</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $0.00</p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning Test </p>
                  <p>ACT </p>
                  <p>CLEP </p>
         </td>
         
         
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Special requirements for nursing and bachelor's degree applicants. Testing requirements for veterinary technology, photography, outdoor recreation leadership, culinary arts, paramedic, and ski area operations. </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>From the college: CMC considers those exams where a CMC course equivalent exists. </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 7</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 5</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 62</p>
                              </td>
                              <td class=col3>
                                 <p> 16</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 10</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Freshman College Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 5</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 5</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 66</p>
                              </td>
                              <td class=col3>
                                 <p> 16</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 10</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 66</p>
                              </td>
                              <td class=col3>
                                 <p> 16</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 10</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   66.0%</p>
                  <p>% of loans / jobs :   34.0%</p>
                  <p>Avg non need-based aid :  $1,451.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Mar 31</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Rita Bayless</p>
                  <p>Financial aid office phone :  (970) 947-8277</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $56.00</p>
                  <p>Cost per credit hour (out-of-state):  $299.00</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Minority Status </p>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>For part-time students </p>
                  <p>Weekends </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>Installment payment </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,980.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,980.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,980.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $9,270.00</p>
                              </td>
                              <td class=col4>
                                 <p> $9,270.00</p>
                              </td>
                              <td class=col4>
                                 <p> $9,270.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $9,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $906.00</p>
                              </td>
                              <td class=col4>
                                 <p> $906.00</p>
                              </td>
                              <td class=col4>
                                 <p> $906.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,200.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $14,286.00</p>
                              </td>
                              <td class=col4>
                                 <p> $5,286.00</p>
                              </td>
                              <td class=col4>
                                 <p> $5,286.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $21,576.00</p>
                              </td>
                              <td class=col4>
                                 <p> $12,576.00</p>
                              </td>
                              <td class=col4>
                                 <p> $12,576.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>

         <table>
            <tbody>
            <h2>Athletic Scholarship Opportunities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Sport</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Male</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Female</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Skiing</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  --</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  --</p>
                  <p>Maximum credits/courses from a 4-year institution:  --</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  2,310</p>
                  <p>Transfers admitted percentage:  100.0%</p>
                  <p>Transfers admitted:  2,310</p>
                  <p>Transfers enrolled percentage:  19.0%</p>
                  <p>Transfers enrolled:  439</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Orientation </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring OUT of this school</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer advisor </p>
                  <p>College fairs/transfer recruitment on campus </p>
                  <p>Transfer center </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>-- </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  May 1</p>
                  <p>Application fee:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $9,270.00</p>
                  <p>Room & Board(on-campus):  $9,000.00</p>
                  <p>Room & Board(off-campus):  --</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $299.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>International students eligible for need based aid </p>
                  <p>International students eligible for non-need based aid </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  --</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Special International Student Orientation Program </p>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>