<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Penn State Berks</h1>
         <h2>Reading, PA</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>Tulpehocken Road </p>
                  <p>Reading, PA 19610-6009 </p>
                  <p>www.bk.psu.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>Tulpehocken Road </p>
                  <p>PO Box 7009 </p>
                  <p>Reading, PA 19610-6009 </p>
                  <p>(610) 396-6060 </p>
                  <p>Fax : (610) 396-6077 </p>
                  <p>admissionsbk@psu.edu </p>
                  <p>Contact : Anne Rohrbach </p>
                  <p>Executive Director for Undergraduate Admissions </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Medium </p>
                  <p>Public </p>
                  <p>branch campus </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>Middle States Association of Colleges and Schools </p>
                  <p>College Board Code: 2660 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Percentage of students graduating within 6 years : 54.0% </p>
                  <p>Total undergraduates : 2,743 </p>
                  <p>First-time degree-seeking freshmen : 814 </p>
                  <p>Percentage of financial need met (average) : 56.0% </p>
                  <p>Average financial aid package : $8,195.00 </p>
                  <p>In-State Tuition : $14,240.00 </p>
                  <p>Out-of-State Tuition : $21,302.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Certificate </p>
                  <p>Associate </p>
                  <p>Bachelor's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small City (50-250k) </p>
                  <p>Suburban </p>
                  <p>Residential campus </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Characteristics</h2>

            <div class="subTabSeperator"></div>
                  <p>Certain bachelor degree programs must be completed at another Penn State campus. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Application rolling begin :   Nov 1</p>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   Nov 30</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   May 1 (or within 2 week(s) if notified after May 1st)</p>
                  <p>Housing deposit due :   May 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   --</p>
                  <p>SAT subject score report due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Feb 15</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   May 1</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   Feb 1</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   17 to 1</p>
                  <p>Degree's Offered in :   Certificate, Associate, Bachelor's degrees</p>
                  <p>Graduating in 6 years :   54.0%</p>
                  <p>Returning for sophomore year :   80.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>Middle States Association of Colleges and Schools </p>
                  <p>Regionally Accredited </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Business/Marketing : 24.0%<br/>Psychology : 12.0%<br/>Education : 11.0%<br/>Communications/Journalism : 10.0%<br/>Computer and Information Sciences : 7.0%<br/>Engineering : 6.0%<br/>Interdisciplinary Studies : 6.0%<br/>Parks And Recreation : 6.0%<br/>Biology : 5.0%<br/></p>
                  <p><b>Associates</b><br/>  Health Professions : 49.0%<br/>Engineering Technologies : 17.0%<br/>Business/Marketing : 15.0%<br/>Liberal Arts : 12.0%<br/>Computer and Information Sciences : 6.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Agriculture & Related Sciences</b><br/>  Agribusiness/Agricultural Business Operations B<br/>Agricultural Mechanization, General B<br/>Agriculture, General B<br/>Animal Sciences, General B<br/>Food Science B<br/>Horticultural Science B<br/>Landscaping and Groundskeeping B<br/>Plant Protection & Integrated Pest Management B<br/>Turf and Turfgrass Management B<br/></p>
                  <p><b>Area, Ethnic, Cultural, & Gender Studies</b><br/>  African-American/Black Studies B<br/>American/United States Studies/Civilization B<br/>Asian Studies/Civilization B C<br/>Latin American Studies B<br/>Women's Studies B<br/></p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biochemistry B<br/>Biology/Biological Sciences, General B<br/>Medical Microbiology and Bacteriology B<br/>Toxicology B<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Actuarial Science C<br/>Business Administration and Management, General C<br/>Business/Commerce, General A B C<br/>Customer Service Management C<br/>E-Commerce/Electronic Commerce C<br/>Entrepreneurship/Entrepreneurial Studies C<br/>Finance, General B<br/>Financial Planning and Services C<br/>Labor Studies C<br/>Labor and Industrial Relations B<br/>Management Information Systems, General B<br/>Marketing/Marketing Management, General B<br/>Organizational Behavior Studies B<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Advertising B C<br/>Communication Studies/Speech Communication and Rhetoric B<br/>Digital Communication and Media/Multimedia C<br/>Journalism B<br/>Public Relations/Image Management C<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer and Information Sciences, General B C<br/>Computer and Information Systems Security B<br/>Information Science/Studies A B<br/>Web Page, Digital/Multimedia and Information Resources Design C<br/></p>
                  <p><b>Education</b><br/>  Adult and Continuing Education Administration B<br/>Agricultural Teacher Education B<br/>Art Teacher Education B<br/>Early Childhood Education and Teaching B<br/>Elementary Education and Teaching B<br/>Foreign Language Teacher  Education B C<br/>Secondary Education and Teaching B<br/>Special Education and Teaching, General B<br/></p>
                  <p><b>Engineering</b><br/>  Aerospace, Aeronautical and Astronautical Engineering B<br/>Agricultural/Biological Engineering and Bioengineering B<br/>Architectural Engineering B<br/>Biomedical/Medical Engineering B<br/>Chemical Engineering B<br/>Civil Engineering, General B<br/>Computer Engineering, General B<br/>Electrical, Electronics and Communications Engineering B C<br/>Engineering Science B<br/>Engineering, General C<br/>Environmental/Environmental Health Engineering B<br/>Industrial Engineering B<br/>Mechanical Engineering B<br/>Mining and Mineral Engineering B<br/>Nuclear Engineering B<br/>Petroleum Engineering B<br/></p>
                  <p><b>Engineering Technologies/Technicians</b><br/>  Biomedical Technology/Technician A<br/>Electrical, Electronic and Communications Engineering  Technology/Technician A<br/>Metallurgical Technology/Technician A<br/>Plastics Engineering Technology/Technician C<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  English Language and Literature, General B<br/>Technical and Business Writing B<br/></p>
                  <p><b>Family, Consumer & Human Sciences</b><br/>  Adult Development and Aging C<br/>Child Development C<br/>Consumer Services and Advocacy C<br/>Human Development and Family Studies, General B<br/>Human Nutrition B<br/></p>
                  <p><b>Foreign Language, Literatures & Linguistics</b><br/>  Chinese Language and Literature B<br/>Classics and Languages, Literatures and Linguistics, General B<br/>Comparative Literature B<br/>Foreign Languages and Literatures, General B<br/>French Language and Literature B<br/>German Language and Literature B<br/>Italian Language and Literature B<br/>Japanese Language and Literature B<br/>Russian Language and Literature B<br/>Spanish Language and Literature B<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Athletic Training/Trainer B<br/>Communication Disorders, General B<br/>Health/Health Care Administration/Management B C<br/>Nursing - Registered Nurse Training (RN, ASN, BSN, MSN) A B<br/>Occupational Therapist Assistant A<br/>Pre-Medicine/Pre-Medical Studies B C<br/>Pre-Veterinary Studies B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Legal Professions & Studies</b><br/>  Legal Studies, General C<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Liberal Arts and Sciences/Liberal Studies A B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/>Statistics, General B<br/></p>
                  <p><b>Multi & Interdisciplinary Studies</b><br/>  Biological and Physical Sciences B<br/>International/global studies C<br/>Medieval and Renaissance Studies B<br/>Science, Technology and Society B<br/></p>
                  <p><b>Natural Resources & Conservation</b><br/>  Environmental Studies B<br/>Forest Sciences and Biology B<br/>Forestry Technology/Technician B<br/>Natural Resources/Conservation, General B<br/></p>
                  <p><b>Parks, Recreation & Fitness Studies</b><br/>  Kinesiology and Exercise Science B<br/>Parks, Recreation and Leisure Facilities Management B<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Jewish/Judaic Studies B<br/>Philosophy B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Astronomy B<br/>Atmospheric Sciences and Meteorology, General B<br/>Chemistry, General B<br/>Geology/Earth Science, General B<br/>Materials Science B<br/>Physics, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B<br/></p>
                  <p><b>Science Technologies & Technicians</b><br/>  Biology Technician/Biotechnology Laboratory Technician B<br/></p>
                  <p><b>Security & Protective Services</b><br/>  Criminal Justice/Law Enforcement Administration B<br/>Criminalistics and Criminal Science C<br/>Forensic Science and Technology B<br/></p>
                  <p><b>Social Sciences</b><br/>  Anthropology B<br/>Archeology B<br/>Economics, General B<br/>Geography B<br/>International Relations and Affairs B<br/>Political Science and Government, General B<br/>Sociology B<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Acting B<br/>Art History, Criticism and Conservation B<br/>Art/Art Studies, General B<br/>Film/Cinema Studies B<br/>Graphic Design B<br/>Music, General B<br/>Technical Theater/Theater Design and Technology B<br/>Visual and Performing Arts, General B<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Accelerated Program </p>
                  <p>Cross-Registration </p>
                  <p>Dual Enrollment of High School Students </p>
                  <p>Honors Program </p>
                  <p>Independent Study </p>
                  <p>Internships </p>
                  <p>Cooperative Education </p>
                  <p>English as a Second Language (ESL) </p>
                  <p>Teacher Certification </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Study Abroad </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Extensive evening or early morning classes </p>
                  <p>Distance Learning </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>311 Public computers, available in: Computer Center, Dorms, Libraries, Student Center </p>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Computer repair service available on campus </p>
                  <p>Student web hosting available </p>
                  <p>Wireless network available </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Medium-sized</p>
                  <p>Geographic Location :   5 miles from downtown.</p>
                  <p>Small City </p>
                  <p>Suburban </p>
                  <p>Residential Campus </p>
                  <p>Total undergraduates :   2,743</p>
                  <p>First-time degree-seeking freshmen :   814</p>
                  <p>Degree-seeking undergrads :   2,577</p>
                  <p>Graduate enrollment :   --</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   21</p>
                  <p>Full time students average age :   20</p>
                  <p>In state students :   92.0%</p>
                  <p>Out of  state students :   8.0%</p>
                  <p>Part Time students :   8.0%</p>
                  <p>Percentage of males :   55.0%</p>
                  <p>Percentage of females :   45.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Two or more races :   2.0%</p>
                  <p>Black African American :   9.0%</p>
                  <p>Asian :   4.0%</p>
                  <p>Hispanic/Latino :   9.0%</p>
                  <p>Race Ethnicity Unknown :   1.0%</p>
                  <p>White :   73.0%</p>
                  <p>Non-Resident Alien :   1.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>Other Activities & Organizations :   All facilities smoke-free.</p>
                  <p>Student Newspaper :   Berks Collegian</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>All undergraduates living in college housing :   29.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Coed Housing </p>
                  <p>Special Housing For Disabled Students </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit :   $100.00</p>
                  <p>Housing deposit due :   May 1</p>
                  <p>Housing deposit is partially refunded if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   NIttany Lions</p>
                  <p>Sport Member :   NCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Club </p>
                  <p>NCAA Division III </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Alcohol/substance abuse counseling </p>
                  <p>Career counseling </p>
                  <p>Economically disadvantaged students services </p>
                  <p>Employment services for undergraduates </p>
                  <p>Financial aid counseling </p>
                  <p>Health services </p>
                  <p>Minority students services </p>
                  <p>Personal counseling </p>
                  <p>Placement services for graduates </p>
                  <p>Adult (re-entering) student services/programs </p>
                  <p>Veteran's counselor </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Wheelchair Accessibility </p>
                  <p>Comprehensive services for students with learning disabilities </p>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Services and/or facilities for speech or communications disorders </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Remedial instruction </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
                  <p>Writing center </p>
                  <p>Pre-admission summer program </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Badminton</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Baseball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Bowling</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cheerleading</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Field Hockey</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football(non-tackle)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Golf</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ice Hockey</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Lacrosse</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Rugby</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Skiing</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Table tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
            </tbody>
         </table>
            <p>Other Sports : floor hockey, aerobics, ultimate medicine ball</p>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $50.00</p>
                  <p>Application fee notes:   Paper/Online</p>
                  <p>Total applicants :   2,570</p>
                  <p>Admitted :   2,135</p>
                  <p>Enrolled :   814</p>
                  <p>Less selective 83.0% of applicants admitted </p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Rigor of secondary school record </p>
         </td>
         
         
         <td class="col2">
            <h2>Considered</h2>

            <div class="subTabSeperator"></div>
                  <p>Alumni Relation </p>
                  <p>Application Essay </p>
                  <p>Character/Personal Qualities </p>
                  <p>Class Rank </p>
                  <p>Extracurricular Activities </p>
                  <p>Recommendations </p>
                  <p>Talent/Ability </p>
                  <p>Volunteer Work </p>
                  <p>Work Experience </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for Admission Decisions</h2>

            <div class="subTabSeperator"></div>
                  <p>Required: SAT or ACT </p>
         </td>
         
         
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning Test </p>
                  <p>AP </p>
                  <p>CLEP </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Admission decisions based upon high school GPA, test scores, class rank, personal statements, and activities. </p>
         </td>
         
         
         <td class="col2">
            <h2>High school class rank of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>Top Tenth :   7.0%</p>
                  <p>Top Quarter :   27.0%</p>
                  <p>Top Half :   65.0%</p>
                  <p>Bottom Half :   35.0%</p>
                  <p>Bottom Quarter :   8.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>GPAs of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>3.75+ :   6.0%</p>
                  <p>3.5 - 3.74 :   11.0%</p>
                  <p>3.25 - 3.49 :   15.0%</p>
                  <p>3.00 - 3.24 :   21.0%</p>
                  <p>2.50 - 2.99 :   34.0%</p>
                  <p>2.00 - 2.49 :   12.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>SAT Critical Reading</h2>

            <div class="subTabSeperator"></div>
                  <p>700 - 800 :   1.0%</p>
                  <p>600 - 699 :   7.0%</p>
                  <p>500 - 599 :   36.0%</p>
                  <p>400 - 499 :   42.0%</p>
                  <p>300 - 399 :   12.0%</p>
                  <p>200 - 299 :   2.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>700 - 800 :   1.0%</p>
                  <p>600 - 699 :   13.0%</p>
                  <p>500 - 599 :   39.0%</p>
                  <p>400 - 499 :   35.0%</p>
                  <p>300 - 399 :   10.0%</p>
                  <p>200 - 299 :   2.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>SAT Writing</h2>

            <div class="subTabSeperator"></div>
                  <p>700 - 800 :   1.0%</p>
                  <p>600 - 699 :   3.0%</p>
                  <p>500 - 599 :   33.0%</p>
                  <p>400 - 499 :   45.0%</p>
                  <p>300 - 399 :   17.0%</p>
                  <p>200 - 299 :   1.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT Composite </h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   2.0%</p>
                  <p>24 - 29 :   29.0%</p>
                  <p>18 - 23 :   53.0%</p>
                  <p>12 - 17 :   16.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   12.0%</p>
                  <p>24 - 29 :   33.0%</p>
                  <p>18 - 23 :   43.0%</p>
                  <p>12 - 17 :   12.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT English</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   4.0%</p>
                  <p>24 - 29 :   18.0%</p>
                  <p>18 - 23 :   53.0%</p>
                  <p>12 - 17 :   23.0%</p>
                  <p>6 - 11 :   2.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>Offers placement into higher-level courses for AP Exams : Yes </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>High school Coursework</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Course Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Recommended</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>High School diploma required, GED accepted</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English</p>
                     </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Math</p>
                     </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science</p>
                     </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Studies</p>
                     </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Foreign Language</p>
                     </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>TEST Scores</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Test Subjects</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Middle 50% of First-Year Students</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Percent who submitted SAT scores : 90.0% and Percent who submitted ACT scores : 6.0%</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Critical Reading</p>
                     </td>
                        <td class=col2>
                              <p> 430 - 530</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Math</p>
                     </td>
                        <td class=col2>
                              <p> 440 - 570</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Writing</p>
                     </td>
                        <td class=col2>
                              <p> 410 - 520</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>ACT Composite</p>
                     </td>
                        <td class=col2>
                              <p> 19 - 25</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>AP & Admission Policy</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Min Score Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Number of Credits</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Equivalent Course(s)</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>From the college: AP Exam scores not used in determining admissibility. GPA weighting that schools might assign to students who take AP or honors courses accepted.</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Art History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ArtH 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Biology</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Bio 011, 012</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Bio 110</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus AB</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Math 140</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Math 140</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Math 140, 141</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chemistry</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Chem 110, 111</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Chem 110, 111, 112, 113</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chinese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Chinese 001, 002</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Chinese 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Comparative Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> PSci 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science A</p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> CS XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science AB</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3*</p>
                              </td>
                              <td class=col4>
                                 <p> CS XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Language and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> --*</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Literature and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Engl 001</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Environmental Science</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Earth 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>European History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Hist 002</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Fr 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 15</p>
                              </td>
                              <td class=col4>
                                 <p> Fr 001, 002, 003, 201</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 18</p>
                              </td>
                              <td class=col4>
                                 <p> Fr 001, 002, 003, 201, 202</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Fr 351</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>German Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Ger 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 16</p>
                              </td>
                              <td class=col4>
                                 <p> Ger 001, 002, 003, 201</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 19*</p>
                              </td>
                              <td class=col4>
                                 <p> Ger 001, 002, 003, 201, 301</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Human Geography</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Geog 020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Italian Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Italian 001, 002</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Italian 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Japanese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Japanese 001, 002</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Japanese 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Lat XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Lat XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Econ 104</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Econ 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Theory</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Mus 008</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics B</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Phys 250, 251</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Electricity and Magnetism</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Phys 212</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Mechanics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Phys 211</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Psychology</p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Psyc 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Language</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 12</p>
                              </td>
                              <td class=col4>
                                 <p> Span 001, 002, 003</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 15</p>
                              </td>
                              <td class=col4>
                                 <p> Span 001, 002, 003 and 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Literature and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Span 253</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Statistics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Stat 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Stat 200</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 2-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Art XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 3-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Art XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: Drawing Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Art XXX</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> PSci 001</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Hist 020, 021</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>World History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Hist 011</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>*Check with the related academic department at the college for more information.<br/><br/></p>

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 62</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 63</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Humanities</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Mathematics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Natural Science</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Pre-calculus</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 63</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   38.0%</p>
                  <p>% of loans / jobs :   62.0%</p>
                  <p>% of freshmen with need who received financial aid :   95.0%</p>
                  <p>% Applied for need-based aid :   85.0%</p>
                  <p>% Judged to have need :   84.0%</p>
                  <p>% that were offered aid :   82.0%</p>
                  <p>% that had need fully met :   4.0%</p>
                  <p>% of need met :   56.0%</p>
                  <p>Average 1st year financial aid package :   $8,195.00</p>
                  <p>Avg non need-based aid :  $1,839.00</p>
                  <p>Avg need-based scholarship or grant award :  $6,489.00</p>
                  <p>Avg need-based loan :  $3,332.00</p>
                  <p>Avg indebtedness at graduation :   $35,100.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Feb 15</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Anna Griswold</p>
                  <p>Financial aid office phone :  (814) 865-6301</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $556.00</p>
                  <p>Cost per credit hour (out-of-state):  $850.00</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
                  <p>ROTC </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>For part-time students </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>Deferred payment </p>
                  <p>External finance company </p>
                  <p>Installment payment </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Army : Offered at a cooperating institution </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $14,240.00</p>
                              </td>
                              <td class=col4>
                                 <p> $14,240.00</p>
                              </td>
                              <td class=col4>
                                 <p> $14,240.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $21,302.00</p>
                              </td>
                              <td class=col4>
                                 <p> $21,302.00</p>
                              </td>
                              <td class=col4>
                                 <p> $21,302.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $11,020.00</p>
                              </td>
                              <td class=col4>
                                 <p> $9,702.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,800.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,568.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,568.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,568.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $3,222.00</p>
                              </td>
                              <td class=col4>
                                 <p> $3,222.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,854.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $918.00</p>
                              </td>
                              <td class=col4>
                                 <p> $918.00</p>
                              </td>
                              <td class=col4>
                                 <p> $2,250.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $30,968.00</p>
                              </td>
                              <td class=col4>
                                 <p> $29,650.00</p>
                              </td>
                              <td class=col4>
                                 <p> $21,712.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $38,030.00</p>
                              </td>
                              <td class=col4>
                                 <p> $36,712.00</p>
                              </td>
                              <td class=col4>
                                 <p> $28,774.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  18</p>
                  <p>Minimum college GPA (on a 4.0 scale):  --</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  --</p>
                  <p>Maximum credits/courses from a 4-year institution:  --</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  36</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>College Transcript(s) </p>
                  <p>High School Transcript </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  379</p>
                  <p>Transfers admitted percentage:  53.0%</p>
                  <p>Transfers admitted:  202</p>
                  <p>Transfers enrolled percentage:  32.0%</p>
                  <p>Transfers enrolled:  122</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>Junior </p>
                  <p>Senior </p>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Pre-admission transcript evaluation (determination of what courses will transfer) </p>
                  <p>Orientation </p>
                  <p>Re-entry advisor </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>-- </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  Feb 1</p>
                  <p>Application fee:  $50.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $21,302.00</p>
                  <p>Room & Board(on-campus):  $11,020.00</p>
                  <p>Room & Board(off-campus):  $9,702.00</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $850.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  80</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Special International Student Orientation Program </p>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>