<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>St. Norbert College</h1>
         <h2>De Pere, WI</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>100 Grant Street </p>
                  <p>De Pere, WI 54115-2099 </p>
                  <p>www.snc.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>100 Grant Street </p>
                  <p>De Pere, WI 54115-2099 </p>
                  <p>(920) 403-3005 </p>
                  <p>Fax : (920) 403-4072 </p>
                  <p>admit@snc.edu </p>
                  <p>Contact : Ed Lamm </p>
                  <p>Executive Director of Enrollment Management and Marketing </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Medium </p>
                  <p>Private </p>
                  <p>liberal arts college </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>College Board Member </p>
                  <p>Roman Catholic Church </p>
                  <p>College Board Code: 1706 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Percentage of students graduating within 6 years : 75.0% </p>
                  <p>Total undergraduates : 2,229 </p>
                  <p>First-time degree-seeking freshmen : 601 </p>
                  <p>Percentage of financial need met (average) : 100.0% </p>
                  <p>Average financial aid package : $25,330.00 </p>
                  <p>In-State Tuition : $31,866.00 </p>
                  <p>Out-of-State Tuition : $31,866.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Bachelor's </p>
                  <p>Master's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Large Town (10-50k) </p>
                  <p>Suburban </p>
                  <p>Residential campus </p>
         </td>
         
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Application rolling begin :   Oct 1</p>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   Apr 1</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   May 1 (or within 3 week(s) if notified after May 1st)</p>
                  <p>Housing deposit due :   May 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   Jul 1</p>
                  <p>SAT subject score report due :   Jul 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Mar 1</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   14 to 1</p>
                  <p>Degree's Offered in :   Bachelor's, Master's degrees</p>
                  <p>Graduating in 6 years :   75.0%</p>
                  <p>Returning for sophomore year :   84.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>Regionally Accredited </p>
                  <p>College Board Member </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Business/Marketing : 25.0%<br/>Education : 12.0%<br/>Communications/Journalism : 11.0%<br/>Social Sciences : 11.0%<br/>Biology : 9.0%<br/>Visual and Performing Arts : 5.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biochemistry B<br/>Biology/Biological Sciences, General B<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Business Administration and Management, General B<br/>Business/Commerce, General B<br/>Finance, General B<br/>Human Resources Management/Personnel Administration, General B<br/>International Business/Trade/Commerce B<br/>Management Information Systems, General B<br/>Marketing/Marketing Management, General B<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Communication Studies/Speech Communication and Rhetoric B<br/>Mass Communication/ Media Studies B<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer Graphics B<br/>Computer Science B<br/></p>
                  <p><b>Education</b><br/>  Early Childhood Education and Teaching B<br/>Education, General M<br/>Elementary Education and Teaching B<br/>Music Teacher Education B<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  Creative Writing B<br/>English Language and Literature, General B<br/></p>
                  <p><b>Foreign Language, Literatures & Linguistics</b><br/>  French Language and Literature B<br/>German Language and Literature B<br/>Spanish Language and Literature B<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Pre-Dentistry Studies B<br/>Pre-Medicine/Pre-Medical Studies B<br/>Pre-Nursing Studies B<br/>Pre-Pharmacy Studies B<br/>Pre-Veterinary Studies B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Legal Professions & Studies</b><br/>  Pre-Law Studies B<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Humanities/Humanistic Studies B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/></p>
                  <p><b>Multi & Interdisciplinary Studies</b><br/>  Biological and Physical Sciences B<br/></p>
                  <p><b>Natural Resources & Conservation</b><br/>  Environmental Science B<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Philosophy B<br/>Religion/Religious Studies B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Chemistry, General B<br/>Geology/Earth Science, General B<br/>Physics, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B<br/></p>
                  <p><b>Public Administration & Social Services</b><br/>  Human Services, General B<br/></p>
                  <p><b>Social Sciences</b><br/>  Anthropology B<br/>Economics, General B<br/>International Relations and Affairs B<br/>Political Science and Government, General B<br/>Sociology B<br/></p>
                  <p><b>Theology & Religious Vocations</b><br/>  Religious Education B<br/>Theology/Theological Studies M<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Art/Art Studies, General B<br/>Commercial and Advertising Art B<br/>Drama and Dramatics/Theater Arts, General B<br/>Graphic Design B<br/>Music, General B<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Double Major </p>
                  <p>English as a Second Language (ESL) </p>
                  <p>Honors Program </p>
                  <p>Independent Study </p>
                  <p>Internships </p>
                  <p>Student-Designed Major </p>
                  <p>Teacher Certification </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Study Abroad </p>
                  <p>Washington Semester </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Distance Learning </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>247 Public computers, available in: Computer Center, Dorms, Libraries, Student Center </p>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Computer repair service available on campus </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Wireless network available </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Medium-sized</p>
                  <p>Unique Facilities :   marina, on-campus hotel and conference center, fine and performing arts centers, center for international education, peace and justice center, center for leadership and service, children's center, women's center, Strategic Research Institute, center for Norbertine studies</p>
                  <p>Geographic Location :   5 miles from Green Bay.</p>
                  <p>Large Town </p>
                  <p>Suburban </p>
                  <p>Residential Campus </p>
                  <p>Total undergraduates :   2,229</p>
                  <p>First-time degree-seeking freshmen :   601</p>
                  <p>Degree-seeking undergrads :   2,189</p>
                  <p>Graduate enrollment :   58</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   20</p>
                  <p>Full time students average age :   20</p>
                  <p>In state students :   75.0%</p>
                  <p>Out of  state students :   25.0%</p>
                  <p>Part Time students :   2.0%</p>
                  <p>Percentage of males :   41.0%</p>
                  <p>Percentage of females :   59.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Two or more races :   1.0%</p>
                  <p>Hispanic/Latino :   3.0%</p>
                  <p>White :   90.0%</p>
                  <p>Non-Resident Alien :   4.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>8.0% Men who Join Fraternities </p>
                  <p>10.0% Women who Join Sororities </p>
                  <p>Student Newspaper :   St. Norbert Times</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>First-year students living in college housing :   99.0%</p>
                  <p>All undergraduates living in college housing :   75.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Apartments For Single Students </p>
                  <p>Coed Housing </p>
                  <p>Special Housing For Disabled Students </p>
                  <p>Special Housing For International Students </p>
                  <p>Women's Housing </p>
                  <p>Wellness Housing (alcohol/drug/smoke-free) </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit :   $100.00</p>
                  <p>Housing deposit due :   May 1</p>
                  <p>Housing deposit is not refunded if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   Green Knights</p>
                  <p>Sport Member :   NCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>NCAA Division III </p>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Club </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Alcohol/substance abuse counseling </p>
                  <p>Chaplain/spiritual director </p>
                  <p>Career counseling </p>
                  <p>Employment services for undergraduates </p>
                  <p>Financial aid counseling </p>
                  <p>Health services </p>
                  <p>Minority students services </p>
                  <p>On-campus daycare </p>
                  <p>Personal counseling </p>
                  <p>Placement services for graduates </p>
                  <p>Women's services </p>
                  <p>Veteran's counselor </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Services and/or facilities for speech or communications disorders </p>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Wheelchair Accessibility </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Reduced course load </p>
                  <p>Remedial instruction </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
                  <p>Writing center </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Badminton</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Baseball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cheerleading</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football(non-tackle)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Golf</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ice Hockey</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Lacrosse</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Rowing (Crew)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Skiing</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track and Field</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Indoor</p>
                     </td>
                        <td class=col2>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Outdoor</p>
                     </td>
                        <td class=col2>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
            </tbody>
         </table>
            <p>Other Sports : ballroom dancing, dodgeball</p>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $25.00</p>
                  <p>Application fee notes:   Paper application (reduced fee for online application)</p>
                  <p>Total applicants :   2,377</p>
                  <p>Admitted :   1,910</p>
                  <p>Enrolled :   601</p>
                  <p>Less selective 80.0% of applicants admitted </p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p>Offered place on waitlist :   30</p>
                  <p>Number accepting place :   25</p>
                  <p>Accepted from list :   13</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Rigor of secondary school record </p>
         </td>
         
         
         <td class="col2">
            <h2>Considered</h2>

            <div class="subTabSeperator"></div>
                  <p>Alumni Relation </p>
                  <p>Application Essay </p>
                  <p>Character/Personal Qualities </p>
                  <p>Class Rank </p>
                  <p>Extracurricular Activities </p>
                  <p>First generation college student </p>
                  <p>Geographical Residence </p>
                  <p>Interview </p>
                  <p>Level of Applicant's Interest </p>
                  <p>Racial/Ethnic Status </p>
                  <p>Recommendations </p>
                  <p>Religious Affiliation or Commitment </p>
                  <p>State Residency </p>
                  <p>Talent/Ability </p>
                  <p>Volunteer Work </p>
                  <p>Work Experience </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for Admission Decisions</h2>

            <div class="subTabSeperator"></div>
                  <p>Required: SAT or ACT </p>
         </td>
         
         
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>Institution's own exam </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>High school record, rigor of courses, and grades earned important. Preference given to students successfully completing challenging courses. Counselor and teacher recommendations, community service considered. Students not in college preparatory programs may be offered admission if test results, class rank, and grades demonstrate aptitude for college work. </p>
         </td>
         
         
         <td class="col2">
            <h2>High school class rank of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>Top Tenth :   25.0%</p>
                  <p>Top Quarter :   58.0%</p>
                  <p>Top Half :   85.0%</p>
                  <p>Bottom Half :   15.0%</p>
                  <p>Bottom Quarter :   3.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>GPAs of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>3.75+ :   34.0%</p>
                  <p>3.5 - 3.74 :   19.0%</p>
                  <p>3.25 - 3.49 :   18.0%</p>
                  <p>3.00 - 3.24 :   11.0%</p>
                  <p>2.50 - 2.99 :   15.0%</p>
                  <p>2.00 - 2.49 :   3.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT Composite </h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   9.0%</p>
                  <p>24 - 29 :   49.0%</p>
                  <p>18 - 23 :   42.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   10.0%</p>
                  <p>24 - 29 :   47.0%</p>
                  <p>18 - 23 :   37.0%</p>
                  <p>12 - 17 :   6.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT English</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   14.0%</p>
                  <p>24 - 29 :   37.0%</p>
                  <p>18 - 23 :   44.0%</p>
                  <p>12 - 17 :   5.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>Offers placement into higher-level courses for AP Exams : Yes </p>
                  <p>From the college: Credit granted for test scores of three, four or five. Each exam qualifies for a minimum of 4 semester credits and may transfer as the equivalent of either a specific course or a general elective, as appropriate. </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>High school Coursework</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Course Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Recommended</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>High School diploma required, GED accepted</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>History</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Math</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science Lab</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Studies</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Foreign Language</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>AP & Admission Policy</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Min Score Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Number of Credits</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Equivalent Course(s)</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Art History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ART 110</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Biology</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> BIOL 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus AB</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 131</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 131 & MATH 132</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chemistry</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> CHEM 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chinese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> MLLS 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Comparative Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> INTL/POLI 160</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science A</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> CSCI 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science AB</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> (2) CSCI 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Language and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Literature and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 150</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Environmental Science</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ENVS 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>European History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 112</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>German Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> GERM 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Human Geography</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> GEOG 225</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Italian Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ITAL 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Japanese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> JAPN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ECON 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ECON 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Theory</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 167</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics B</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 111</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Electricity and Magnetism</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Mechanics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 121</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Psychology</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PSYC 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Language</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Literature and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Statistics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> SSCI 224</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 2-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ART 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 3-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ART 135</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: Drawing Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> ART 134</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> POLI 130</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 116</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>World History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 113</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Freshman College Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   65.0%</p>
                  <p>% of loans / jobs :   35.0%</p>
                  <p>% of freshmen with need who received financial aid :   100.0%</p>
                  <p>% Applied for need-based aid :   81.0%</p>
                  <p>% Judged to have need :   86.0%</p>
                  <p>% that were offered aid :   86.0%</p>
                  <p>% that had need fully met :   25.0%</p>
                  <p>% of need met :   100.0%</p>
                  <p>Average 1st year financial aid package :   $25,330.00</p>
                  <p>Avg non need-based aid :  $10,291.00</p>
                  <p>Avg need-based scholarship or grant award :  $21,146.00</p>
                  <p>Avg need-based loan :  $3,759.00</p>
                  <p>Avg indebtedness at graduation :   $31,331.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Mar 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Jeff Zahn</p>
                  <p>Financial aid office phone :  (800) 786-6721</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $977.00</p>
                  <p>Cost per credit hour (out-of-state):  --</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Art </p>
                  <p>Leadership </p>
                  <p>Minority Status </p>
                  <p>Music/Drama </p>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Art </p>
                  <p>Leadership </p>
                  <p>Minority Status </p>
                  <p>Music/Drama </p>
                  <p>ROTC </p>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>For part-time students </p>
                  <p>Weekends </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>External finance company </p>
                  <p>Installment payment </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Army : Offered at a cooperating institution </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $31,866.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $8,126.00</p>
                              </td>
                              <td class=col4>
                                 <p> $4,526.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,168.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $950.00</p>
                              </td>
                              <td class=col4>
                                 <p> $950.00</p>
                              </td>
                              <td class=col4>
                                 <p> $950.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $750.00</p>
                              </td>
                              <td class=col4>
                                 <p> $750.00</p>
                              </td>
                              <td class=col4>
                                 <p> $622.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $350.00</p>
                              </td>
                              <td class=col4>
                                 <p> $650.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,650.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $42,042.00</p>
                              </td>
                              <td class=col4>
                                 <p> $38,742.00</p>
                              </td>
                              <td class=col4>
                                 <p> $36,256.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $42,042.00</p>
                              </td>
                              <td class=col4>
                                 <p> $38,742.00</p>
                              </td>
                              <td class=col4>
                                 <p> $36,256.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  --</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2.5</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  72</p>
                  <p>Maximum credits/courses from a 4-year institution:  96</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>Essay or Personal Statement </p>
                  <p>Standardized Test Scores </p>
                  <p>College Transcript(s) </p>
                  <p>High School Transcript </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  112</p>
                  <p>Transfers admitted percentage:  76.0%</p>
                  <p>Transfers admitted:  86</p>
                  <p>Transfers enrolled percentage:  38.0%</p>
                  <p>Transfers enrolled:  43</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Winter </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
                  <p>Junior </p>
                  <p>Senior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Orientation </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>Emphasis on rigor of college courses and grades received. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Application fee:  $50.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $31,866.00</p>
                  <p>Room & Board(on-campus):  $8,126.00</p>
                  <p>Room & Board(off-campus):  $4,526.00</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $977.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>International students eligible for need based aid </p>
                  <p>International students eligible for non-need based aid </p>
                  <p>Total Amount Awarded:  $1,800,410.00</p>
                  <p>Number of enrolled international undergraduates received aid:  106</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  --</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>English as a Second Language Program On Campus for International Students </p>
                  <p>Special International Student Orientation Program </p>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>