<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Lincoln Memorial University</h1>
         <h2>Harrogate, TN</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>6965 Cumberland Gap Parkway </p>
                  <p>Harrogate, TN 37752-1901 </p>
                  <p>www.lmunet.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>6965 Cumberland Gap Parkway </p>
                  <p>Harrogate, TN 37752-1901 </p>
                  <p>(423) 869-3611 </p>
                  <p>Fax : (423) 869-6444 </p>
                  <p>admissions@lmunet.edu </p>
                  <p>Contact : Bryan Erslan </p>
                  <p>Dean of Admissions </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Small </p>
                  <p>Private </p>
                  <p>university </p>
                  <p>liberal arts college </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>College Board Member </p>
                  <p>College Board Code: 1408 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Total undergraduates : 1,851 </p>
                  <p>First-time degree-seeking freshmen : 253 </p>
                  <p>Percentage of financial need met (average) : 87.0% </p>
                  <p>Average financial aid package : $21,243.00 </p>
                  <p>In-State Tuition : $19,460.00 </p>
                  <p>Out-of-State Tuition : $19,460.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Associate </p>
                  <p>Bachelor's </p>
                  <p>Master's </p>
                  <p>Doctoral </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small Town (2,500-10k) </p>
                  <p>Rural </p>
                  <p>Commuter campus </p>
         </td>
         
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Application rolling begin :   Sep 1</p>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   Jun 1</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   Jun 1</p>
                  <p>SAT subject score report due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Feb 15</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   Aug 1</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   Jun 1</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   Jun 1</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   13 to 1</p>
                  <p>Degree's Offered in :   Associate, Bachelor's, Master's, Doctoral degrees</p>
                  <p>Returning for sophomore year :   66.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>College Board Member </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Health Professions : 33.0%<br/>Business/Marketing : 31.0%<br/>Education : 9.0%<br/>Parks And Recreation : 6.0%<br/></p>
                  <p><b>Associates</b><br/>  Health Professions : 100.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Area, Ethnic, Cultural, & Gender Studies</b><br/>  American/United States Studies/Civilization B<br/></p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biology/Biological Sciences, General B<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Business Administration and Management, General B M<br/>Business/Commerce, General B M<br/>Business/Managerial Economics B<br/>General Office Occupations and Clerical Services B<br/>Management Science, General B<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Communication Studies/Speech Communication and Rhetoric B<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer and Information Sciences, General B<br/></p>
                  <p><b>Education</b><br/>  Art Teacher Education B<br/>Biology Teacher Education B<br/>Business Teacher Education B<br/>Chemistry Teacher Education B<br/>Counselor Education/School Counseling and Guidance Services D M<br/>Curriculum and Instruction M<br/>Early Childhood Education and Teaching B<br/>Education, General B<br/>Educational Leadership and Administration, General D M<br/>Elementary Education and Teaching B<br/>English/Language Arts Teacher Education B<br/>Health Teacher Education B<br/>History Teacher Education B<br/>Junior High/Intermediate/Middle School Education and Teaching B<br/>Mathematics Teacher Education B<br/>Physical Education Teaching and Coaching B<br/>Science Teacher Education/General Science Teacher Education B<br/>Secondary Education and Teaching B<br/>Social Science Teacher Education B<br/>Social Studies Teacher Education B<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  English Language and Literature, General B<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Athletic Training/Trainer B<br/>Clinical Laboratory Science/Medical Technology/Technologist B<br/>Clinical/Medical Laboratory Technician B<br/>Nursing - Registered Nurse Training (RN, ASN, BSN, MSN) A B<br/>Pre-Dentistry Studies B<br/>Pre-Medicine/Pre-Medical Studies B<br/>Pre-Pharmacy Studies B<br/>Pre-Veterinary Studies B<br/>Veterinary/Animal Health Technology/Technician and Veterinary Assistant A B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Legal Professions & Studies</b><br/>  Legal Studies, General D<br/>Pre-Law Studies B<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Humanities/Humanistic Studies B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/></p>
                  <p><b>Natural Resources & Conservation</b><br/>  Environmental Science B<br/>Wildlife and Wildlands Science and Management B<br/></p>
                  <p><b>Parks, Recreation & Fitness Studies</b><br/>  Health and Physical Education, General B<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Philosophy and Religious Studies, General B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Chemistry, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B<br/></p>
                  <p><b>Public Administration & Social Services</b><br/>  Social Work B<br/></p>
                  <p><b>Security & Protective Services</b><br/>  Criminal Justice/Law Enforcement Administration B<br/></p>
                  <p><b>Social Sciences</b><br/>  Social Sciences, General B<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Art/Art Studies, General B<br/>Visual and Performing Arts, General B<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Internships </p>
                  <p>Teacher Certification </p>
                  <p>Double Major </p>
                  <p>English as a Second Language (ESL) </p>
                  <p>Dual Enrollment of High School Students </p>
                  <p>Honors Program </p>
                  <p>Independent Study </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Available</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Army </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Extensive evening or early morning classes </p>
                  <p>Distance Learning </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Wireless network available </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Small</p>
                  <p>Unique Facilities :   Abraham Lincoln library and museum, mountain research center, driving range</p>
                  <p>Geographic Location :   50 miles from Knoxville.</p>
                  <p>Small Town </p>
                  <p>Rural </p>
                  <p>Commuter Campus </p>
                  <p>Total undergraduates :   1,851</p>
                  <p>First-time degree-seeking freshmen :   253</p>
                  <p>Degree-seeking undergrads :   1,749</p>
                  <p>Graduate enrollment :   2,487</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   24</p>
                  <p>Full time students average age :   23</p>
                  <p>In state students :   75.0%</p>
                  <p>Out of  state students :   25.0%</p>
                  <p>Part Time students :   22.0%</p>
                  <p>Percentage of males :   27.0%</p>
                  <p>Percentage of females :   73.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Black African American :   4.0%</p>
                  <p>Hispanic/Latino :   2.0%</p>
                  <p>Race Ethnicity Unknown :   10.0%</p>
                  <p>White :   80.0%</p>
                  <p>Non-Resident Alien :   2.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>3.0% Men who Join Fraternities </p>
                  <p>4.0% Women who Join Sororities </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>First-year students living in college housing :   70.0%</p>
                  <p>All undergraduates living in college housing :   37.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Apartments For Married Students </p>
                  <p>Apartments For Single Students </p>
                  <p>Coed Housing </p>
                  <p>Men's Housing </p>
                  <p>Special Housing For Disabled Students </p>
                  <p>Women's Housing </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit :   $200.00</p>
                  <p>Housing deposit is refundable in full if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   Railsplitters</p>
                  <p>Sport Member :   NCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>NCAA Division II </p>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Scholarship </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Alcohol/substance abuse counseling </p>
                  <p>Career counseling </p>
                  <p>Financial aid counseling </p>
                  <p>Personal counseling </p>
                  <p>Placement services for graduates </p>
                  <p>Chaplain/spiritual director </p>
                  <p>Employment services for undergraduates </p>
                  <p>Health services </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Wheelchair Accessibility </p>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Services and/or facilities for visually impaired </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Reduced course load </p>
                  <p>Remedial instruction </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
                  <p>Writing center </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Baseball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Men's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division II</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cheerleading</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's NCAA Division II</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football(non-tackle)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Golf</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's NCAA Division II</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division II</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Swimming</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Table tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division II</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ultimate Frisbee</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division II</p>
                        </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $25.00</p>
                  <p>Application fee notes:   Paper application (no fee for online application)</p>
                  <p>Total applicants :   984</p>
                  <p>Admitted :   642</p>
                  <p>Enrolled :   253</p>
                  <p>Somewhat selective 65.0% of applicants admitted </p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Rigor of secondary school record </p>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Alumni Relation </p>
                  <p>Character/Personal Qualities </p>
                  <p>Class Rank </p>
         </td>
         
         
         <td class="col2">
            <h2>Considered</h2>

            <div class="subTabSeperator"></div>
                  <p>Extracurricular Activities </p>
                  <p>First generation college student </p>
                  <p>Racial/Ethnic Status </p>
                  <p>Volunteer Work </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for Admission Decisions</h2>

            <div class="subTabSeperator"></div>
                  <p>Required: SAT or ACT </p>
         </td>
         
         
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning Test </p>
                  <p>ACT </p>
                  <p>CLEP </p>
                  <p>Institution's own exam </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic record, ACT or SAT very important. </p>
         </td>
         
         
         <td class="col2">
            <h2>GPAs of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>3.75+ :   27.0%</p>
                  <p>3.5 - 3.74 :   23.0%</p>
                  <p>3.25 - 3.49 :   19.0%</p>
                  <p>3.00 - 3.24 :   16.0%</p>
                  <p>2.50 - 2.99 :   10.0%</p>
                  <p>2.00 - 2.49 :   5.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT Critical Reading</h2>

            <div class="subTabSeperator"></div>
                  <p>600 - 699 :   20.0%</p>
                  <p>500 - 599 :   40.0%</p>
                  <p>400 - 499 :   29.0%</p>
                  <p>300 - 399 :   11.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>SAT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>600 - 699 :   23.0%</p>
                  <p>500 - 599 :   26.0%</p>
                  <p>400 - 499 :   45.0%</p>
                  <p>300 - 399 :   6.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT Composite </h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   7.0%</p>
                  <p>24 - 29 :   26.0%</p>
                  <p>18 - 23 :   57.0%</p>
                  <p>12 - 17 :   10.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>From the college: LMU follows the ACE guidelines with exception.  The department may override the ACE quidelines.  The Registrar's Office is notified of the department guidelines.  These department guidelines apply to all students who take exams that transfer as courses which fall under the corresponding department. </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>High school Coursework</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Course Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Recommended</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>High School diploma required, GED accepted</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Visual/Performing Arts</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>History</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English</p>
                     </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Math</p>
                     </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science</p>
                     </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Studies</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Foreign Language</p>
                     </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Academic Electives</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>TEST Scores</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Test Subjects</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Middle 50% of First-Year Students</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Percent who submitted SAT scores : 12.0% and Percent who submitted ACT scores : 85.0%</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Critical Reading</p>
                     </td>
                        <td class=col2>
                              <p> 420 - 550</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Math</p>
                     </td>
                        <td class=col2>
                              <p> 430 - 560</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>ACT Composite</p>
                     </td>
                        <td class=col2>
                              <p> 20 - 25</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>AP & Admission Policy</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Min Score Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Number of Credits</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Equivalent Course(s)</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Art History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Biology</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> Biol 111 and B111 Lab  and Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus AB</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> Math 130</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> Math 130</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chemistry</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Chem 111 and 
Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chinese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Comparative Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science A</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science AB</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Language and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Engl 110 and Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Literature and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Environmental Science</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>European History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Fren 111 and Fren 112</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>German Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Human Geography</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Geog 211</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Italian Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Japanese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit
</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Econ 211</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Econ 212</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Aural Subscore</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Theory</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Musc 111 and Musc 112</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics B</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Electricity and Magnetism</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit
</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Mechanics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Psychology</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Psyc 100
</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Language</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Span 111 and Span 112</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Literature and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Statistics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Math 270</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 2-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Art 110
</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 3-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Art 205</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: Drawing Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Elective Credit</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> Govt 211</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Hist 131 and Hist 132</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>World History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> Hist 121 and Hist 122</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 51</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 41</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Composition</p>
                     </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 42</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Freshman College Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 44</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 42</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 36</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Humanities</p>
                     </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 52</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 44</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Mathematics</p>
                     </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 41</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Natural Science</p>
                     </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Sciences and History</p>
                     </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Fourth Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 12</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 45</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 46</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 47</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   68.0%</p>
                  <p>% of loans / jobs :   32.0%</p>
                  <p>% of freshmen with need who received financial aid :   100.0%</p>
                  <p>% Applied for need-based aid :   99.0%</p>
                  <p>% Judged to have need :   89.0%</p>
                  <p>% that were offered aid :   89.0%</p>
                  <p>% that had need fully met :   9.0%</p>
                  <p>% of need met :   87.0%</p>
                  <p>Average 1st year financial aid package :   $21,243.00</p>
                  <p>Avg non need-based aid :  $1,500.00</p>
                  <p>Avg need-based scholarship or grant award :  $4,200.00</p>
                  <p>Avg need-based loan :  $2,000.00</p>
                  <p>Avg indebtedness at graduation :   $22,439.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Feb 15</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Bryan Erslan</p>
                  <p>Financial aid office phone :  (423) 869-6336</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $790.00</p>
                  <p>Cost per credit hour (out-of-state):  --</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
                  <p>Athletics </p>
                  <p>Music/Drama </p>
                  <p>ROTC </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>External finance company </p>
                  <p>Installment payment </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Army : Offered on Campus </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                              <td class=col4>
                                 <p> $19,460.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $6,740.00</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,250.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,250.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,250.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                              <td class=col4>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $27,450.00</p>
                              </td>
                              <td class=col4>
                                 <p> $20,710.00</p>
                              </td>
                              <td class=col4>
                                 <p> $20,710.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $27,450.00</p>
                              </td>
                              <td class=col4>
                                 <p> $20,710.00</p>
                              </td>
                              <td class=col4>
                                 <p> $20,710.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>

         <table>
            <tbody>
            <h2>Athletic Scholarship Opportunities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Sport</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Male</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Female</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Baseball</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Basketball</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Cross-Country</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Golf</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Soccer</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Softball</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Tennis</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Volleyball</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  12</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  49</p>
                  <p>Maximum credits/courses from a 4-year institution:  96</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  32</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>College Transcript(s) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Recommended)</h2>

            <div class="subTabSeperator"></div>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
                  <p>Junior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Orientation </p>
                  <p>Pre-admission transcript evaluation (determination of what courses will transfer) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>Developmental or remedial courses not accepted. Submit current immunization records. If requested, submit letters of recommendation. </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  Jun 1</p>
                  <p>Application fee:  $25.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $19,460.00</p>
                  <p>Room & Board(on-campus):  $6,740.00</p>
                  <p>Room & Board(off-campus):  --</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $790.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>International students eligible for non-need based aid </p>
                  <p>Total Amount Awarded:  $288,471.00</p>
                  <p>Number of enrolled international undergraduates received aid:  42</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  --</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Special International Student Orientation Program </p>
                  <p>English as a Second Language Program On Campus for International Students </p>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>