<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Albion College</h1>
         <h2>Albion, MI</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>611 East Porter Street </p>
                  <p>Albion, MI 49224 </p>
                  <p>www.albion.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>611 East Porter Street </p>
                  <p>Albion, MI 49224-1831 </p>
                  <p>(517) 629-0321 </p>
                  <p>Fax : (517) 629-0569 </p>
                  <p>admission@albion.edu </p>
                  <p>Contact : Peter Lttlefield </p>
                  <p>Director of Admissions </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Small </p>
                  <p>Private </p>
                  <p>liberal arts college </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>College Board Member </p>
                  <p>United Methodist Church </p>
                  <p>College Board Code: 1007 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Percentage of students graduating within 6 years : 72.0% </p>
                  <p>Total undergraduates : 1,382 </p>
                  <p>First-time degree-seeking freshmen : 360 </p>
                  <p>Percentage of financial need met (average) : 81.0% </p>
                  <p>Average financial aid package : $26,742.00 </p>
                  <p>In-State Tuition : $35,866.00 </p>
                  <p>Out-of-State Tuition : $35,866.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Bachelor's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small Town (2,500-10k) </p>
                  <p>Rural </p>
                  <p>Residential campus </p>
         </td>
         
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Application rolling begin :   Nov 1</p>
                  <p>Regular application due:   No Regular Application Deadline</p>
                  <p>Priority application due :   Dec 1</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Early Decision And Action</h2>

            <div class="subTabSeperator"></div>
                  <p>Early action application due :   Dec 1</p>
                  <p>College will notify student of early action admission by :   Dec 15</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   Jun 1</p>
                  <p>SAT subject score report due :   Jun 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Feb 1</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   --</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   Mar 1</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   11 to 1</p>
                  <p>Degree's Offered in :   Bachelor's degrees</p>
                  <p>Graduating in 6 years :   72.0%</p>
                  <p>Returning for sophomore year :   73.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>North Central Association of Colleges and Schools </p>
                  <p>Regionally Accredited </p>
                  <p>College Board Member </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Social Sciences : 19.0%<br/>Biology : 13.0%<br/>Physical Sciences : 9.0%<br/>Business/Marketing : 8.0%<br/>Psychology : 8.0%<br/>Communications/Journalism : 7.0%<br/>Education : 5.0%<br/>History : 5.0%<br/>Visual and Performing Arts : 5.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Area, Ethnic, Cultural, & Gender Studies</b><br/>  American/United States Studies/Civilization B<br/></p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biochemistry B<br/>Biology/Biological Sciences, General B<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Accounting B<br/>Business Administration and Management, General B<br/>Finance, General B<br/>Human Resources Management/Personnel Administration, General B<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Communication Studies/Speech Communication and Rhetoric B<br/></p>
                  <p><b>Education</b><br/>  Art Teacher Education B<br/>Biology Teacher Education B<br/>Chemistry Teacher Education B<br/>English/Language Arts Teacher Education B<br/>Foreign Language Teacher  Education B<br/>French Language Teacher Education B<br/>German Language Teacher Education B<br/>History Teacher Education B<br/>Mathematics Teacher Education B<br/>Music Teacher Education B<br/>Physics Teacher Education B<br/>Psychology Teacher  Education B<br/>Science Teacher Education/General Science Teacher Education B<br/>Social Studies Teacher Education B<br/>Spanish Language Teacher Education B<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  Creative Writing B<br/>English Language and Literature, General B<br/></p>
                  <p><b>Foreign Language, Literatures & Linguistics</b><br/>  French Language and Literature B<br/>German Language and Literature B<br/>Spanish Language and Literature B<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Athletic Training/Trainer B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  Liberal Arts and Sciences/Liberal Studies B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/></p>
                  <p><b>Multi & Interdisciplinary Studies</b><br/>  Behavioral Sciences B<br/>Biological and Physical Sciences B<br/>Mathematics and Computer Science B<br/>Natural Sciences B<br/></p>
                  <p><b>Natural Resources & Conservation</b><br/>  Environmental Science B<br/>Environmental Studies B<br/></p>
                  <p><b>Parks, Recreation & Fitness Studies</b><br/>  Kinesiology and Exercise Science B<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Philosophy B<br/>Religion/Religious Studies B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Chemistry, General B<br/>Geology/Earth Science, General B<br/>Physics, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B<br/></p>
                  <p><b>Public Administration & Social Services</b><br/>  Public Policy Analysis B<br/></p>
                  <p><b>Social Sciences</b><br/>  Anthropology B<br/>Economics, General B<br/>International Economics B<br/>International Relations and Affairs B<br/>Political Science and Government, General B<br/>Sociology B<br/>Sociology and Anthropology B<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Art History, Criticism and Conservation B<br/>Art/Art Studies, General B<br/>Drama and Dramatics/Theater Arts, General B<br/>Fine/Studio Arts, General B<br/>Music Performance, General B<br/>Music, General B<br/>Visual and Performing Arts, General B<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Double Major </p>
                  <p>Dual Enrollment of High School Students </p>
                  <p>Honors Program </p>
                  <p>Independent Study </p>
                  <p>Internships </p>
                  <p>Liberal Arts/Career Combination </p>
                  <p>Student-Designed Major </p>
                  <p>Teacher Certification </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>New York Semester </p>
                  <p>Semester At Sea </p>
                  <p>Study Abroad </p>
                  <p>Urban Semester </p>
                  <p>Washington Semester </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>410 Public computers, available in: Computer Center, Dorms, Libraries, Student Center </p>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Computer repair service available on campus </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Wireless network available </p>
                  <p>Student web hosting available </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Where Graduates Go</h2>

            <div class="subTabSeperator"></div>
                  <p>Within one year of receiving their bachelor’s degree: <br/> </p>
                  <p>Law :   5.0%</p>
                  <p>Medical :   7.0%</p>
                  <p>Other :   12.0%</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Small</p>
                  <p>Unique Facilities :   science complex, 144-acre nature center, observatory, equestrian center</p>
                  <p>Geographic Location :   55 miles from Lansing, 55 miles from Ann Arbor.</p>
                  <p>Small Town </p>
                  <p>Rural </p>
                  <p>Residential Campus </p>
                  <p>Total undergraduates :   1,382</p>
                  <p>First-time degree-seeking freshmen :   360</p>
                  <p>Degree-seeking undergrads :   1,355</p>
                  <p>Graduate enrollment :   --</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   20</p>
                  <p>Full time students average age :   20</p>
                  <p>In state students :   91.0%</p>
                  <p>Out of  state students :   9.0%</p>
                  <p>Part Time students :   <1%</p>
                  <p>Percentage of males :   51.0%</p>
                  <p>Percentage of females :   49.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Two or more races :   4.0%</p>
                  <p>Black African American :   4.0%</p>
                  <p>Asian :   1.0%</p>
                  <p>Hispanic/Latino :   3.0%</p>
                  <p>Race Ethnicity Unknown :   3.0%</p>
                  <p>White :   81.0%</p>
                  <p>Non-Resident Alien :   4.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>Other Activities & Organizations :   All students are required to reside and board within the College residential system.  Exemptions are granted to students commuting from home (defined as those students who reside with their parents or legal guardians within 50 miles of the campus), married students, students with legal dependents, students age 23 or older (housing can be provided if desired), and United States veterans.</p>
                  <p>51.0% Men who Join Fraternities </p>
                  <p>43.0% Women who Join Sororities </p>
                  <p>Student Newspaper :   The Pleiad</p>
                  <p>Student Newspaper URL :   http://www.albionpleiad.com</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>First-year students living in college housing :   93.0%</p>
                  <p>All undergraduates living in college housing :   90.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Apartments For Married Students </p>
                  <p>Apartments For Single Students </p>
                  <p>Coed Housing </p>
                  <p>Fraternity/Sorority Housing </p>
                  <p>Men's Housing </p>
                  <p>Special Housing For Disabled Students </p>
                  <p>Women's Housing </p>
                  <p>Theme Housing </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit is partially refunded if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   Britons</p>
                  <p>Sport Member :   NCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>NCAA Division III </p>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Club </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Alcohol/substance abuse counseling </p>
                  <p>Chaplain/spiritual director </p>
                  <p>Career counseling </p>
                  <p>Employment services for undergraduates </p>
                  <p>Financial aid counseling </p>
                  <p>Health services </p>
                  <p>Minority students services </p>
                  <p>Personal counseling </p>
                  <p>Placement services for graduates </p>
                  <p>Women's services </p>
                  <p>Economically disadvantaged students services </p>
                  <p>Veteran's counselor </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Wheelchair Accessibility </p>
                  <p>Services and/or facilities for speech or communications disorders </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Reduced course load </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
                  <p>Writing center </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Baseball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cheerleading</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Diving</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Equestrian</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football(non-tackle)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Golf</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ice Hockey</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Lacrosse</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Racquetball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Rugby</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sailing</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Swimming</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track and Field</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Indoor</p>
                     </td>
                        <td class=col2>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Outdoor</p>
                     </td>
                        <td class=col2>
                              <p> Men's NCAA Division III</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Ultimate Frisbee</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's Club</p>
                              <p> Women's NCAA Division III</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Water Polo</p>
                     </td>
                        <td class=col2>
                              <p> Men's Club</p>
                              <p> Women's Club</p>
                        </td>
                  </tr>
            </tbody>
         </table>
            <p>Other Sports : canoe club - men & women</p>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $0.00</p>
                  <p>Total applicants :   2,383</p>
                  <p>Admitted :   1,673</p>
                  <p>Enrolled :   360</p>
                  <p>Somewhat selective 70.0% of applicants admitted </p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   1,218</p>
                  <p>Admitted early action :   972</p>
                  <p>Plan Available for early admission :   Early action - not restrictive</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Rigor of secondary school record </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Essay </p>
                  <p>Recommendations </p>
                  <p>Standardized Test Scores </p>
         </td>
         
         
         <td class="col2">
            <h2>Considered</h2>

            <div class="subTabSeperator"></div>
                  <p>Alumni Relation </p>
                  <p>Character/Personal Qualities </p>
                  <p>Class Rank </p>
                  <p>Extracurricular Activities </p>
                  <p>Interview </p>
                  <p>Level of Applicant's Interest </p>
                  <p>Talent/Ability </p>
                  <p>Volunteer Work </p>
                  <p>Work Experience </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for Admission Decisions</h2>

            <div class="subTabSeperator"></div>
                  <p>Required: SAT or ACT </p>
         </td>
         
         
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>AP </p>
                  <p>CLEP </p>
                  <p>Institution's own exam </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Highest Section Scores Across Test Dates  </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>Information not supplied by college </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Admission based on school achievement record, ACT/SAT test scores, recommendations from counselor or principal. </p>
         </td>
         
         
         <td class="col2">
            <h2>GPAs of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>3.75+ :   25.0%</p>
                  <p>3.5 - 3.74 :   19.0%</p>
                  <p>3.25 - 3.49 :   23.0%</p>
                  <p>3.00 - 3.24 :   15.0%</p>
                  <p>2.50 - 2.99 :   15.0%</p>
                  <p>2.00 - 2.49 :   3.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT Critical Reading</h2>

            <div class="subTabSeperator"></div>
                  <p>700 - 800 :   6.0%</p>
                  <p>600 - 699 :   26.0%</p>
                  <p>500 - 599 :   29.0%</p>
                  <p>400 - 499 :   39.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>SAT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>700 - 800 :   16.0%</p>
                  <p>600 - 699 :   23.0%</p>
                  <p>500 - 599 :   32.0%</p>
                  <p>400 - 499 :   23.0%</p>
                  <p>300 - 399 :   6.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT Composite </h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   14.0%</p>
                  <p>24 - 29 :   38.0%</p>
                  <p>18 - 23 :   40.0%</p>
                  <p>12 - 17 :   7.0%</p>
                  <p>6 - 11 :   1.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   11.0%</p>
                  <p>24 - 29 :   48.0%</p>
                  <p>18 - 23 :   37.0%</p>
                  <p>12 - 17 :   4.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT English</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   10.0%</p>
                  <p>24 - 29 :   46.0%</p>
                  <p>18 - 23 :   36.0%</p>
                  <p>12 - 17 :   8.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>Offers placement into higher-level courses for AP Exams : Yes </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>High school Coursework</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Course Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Recommended</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>High School diploma required, GED accepted</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>History</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Math</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science Lab</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Studies</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Foreign Language</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Academic Electives</p>
                     </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>TEST Scores</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Test Subjects</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Middle 50% of First-Year Students</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Percent who submitted SAT scores : 8.0% and Percent who submitted ACT scores : 94.0%</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Critical Reading</p>
                     </td>
                        <td class=col2>
                              <p> 460 - 620</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Math</p>
                     </td>
                        <td class=col2>
                              <p> 480 - 640</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Writing</p>
                     </td>
                        <td class=col2>
                              <p> 490 - 580</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>ACT Composite</p>
                     </td>
                        <td class=col2>
                              <p> 22 - 27</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>AP & Admission Policy</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Min Score Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Number of Credits</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Equivalent Course(s)</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Art History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> ARTH 112</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Biology</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> BIOL 190</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus AB</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 141</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> --*</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 141, 143</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1*</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 141, 143</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2*</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 141, 143</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC: AB Subscore</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 141</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chemistry</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> CHEM 121</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chinese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MLAC 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Comparative Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PLSC 190</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science A</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> CS 171</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science AB</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> CS 171</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Language and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 101 & WCE</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Literature and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 151 & WCE</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Environmental Science</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> ENVN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>European History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 103</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 101,102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 102, 201</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>German Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> GERM 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> GERM 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> GERM 101,102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Human Geography</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 0.75</p>
                              </td>
                              <td class=col4>
                                 <p> AS 190</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Italian Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MLAC 100</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Japanese Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> JAPN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> JAPN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> JAPN 101 & 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 101,102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> LATN 102, 201</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> EM 191</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> EM 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> EM 190</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> EM 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Theory</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics B</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 115</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Electricity and Magnetism</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 168</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Mechanics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 167</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Psychology</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PSYC 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Language</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 101,102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Literature and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1.5</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 101,102</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Statistics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 209</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 2-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1*</p>
                              </td>
                              <td class=col4>
                                 <p> ART 192</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 3-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1*</p>
                              </td>
                              <td class=col4>
                                 <p> ART 193</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: Drawing Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1*</p>
                              </td>
                              <td class=col4>
                                 <p> ART 191</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> PLSC 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 101</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>World History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 190</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>*Check with the related academic department at the college for more information.<br/><br/></p>

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Accounting, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra - Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Freshman College Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Trigonometry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> --</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   71.0%</p>
                  <p>% of loans / jobs :   29.0%</p>
                  <p>% of freshmen with need who received financial aid :   100.0%</p>
                  <p>% Applied for need-based aid :   78.0%</p>
                  <p>% Judged to have need :   89.0%</p>
                  <p>% that were offered aid :   89.0%</p>
                  <p>% that had need fully met :   19.0%</p>
                  <p>% of need met :   81.0%</p>
                  <p>Average 1st year financial aid package :   $26,742.00</p>
                  <p>Avg non need-based aid :  $16,731.00</p>
                  <p>Avg need-based scholarship or grant award :  $21,465.00</p>
                  <p>Avg need-based loan :  $5,392.00</p>
                  <p>Avg indebtedness at graduation :   $36,029.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Feb 1</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Ann Whitmer</p>
                  <p>Financial aid office phone :  (517) 629-0440</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $1,500.00</p>
                  <p>Cost per credit hour (out-of-state):  --</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Scholarship Opportunities</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic scholarships, range from $16,000 -$19,000 per year ($64,000 to $76,000 over four years), renewable each year subject to satisfactory progress,  awarded to students with outstanding academic records or unique skills, talents, or abilities. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
                  <p>Art </p>
                  <p>Leadership </p>
                  <p>Music/Drama </p>
                  <p>Religious Affiliation </p>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Alumni Affiliation </p>
                  <p>Art </p>
                  <p>Leadership </p>
                  <p>Music/Drama </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>Weekends </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>Deferred payment </p>
                  <p>External finance company </p>
                  <p>Installment payment </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                              <td class=col4>
                                 <p> $35,866.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $10,144.00</p>
                              </td>
                              <td class=col4>
                                 <p> $10,144.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,000.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $900.00</p>
                              </td>
                              <td class=col4>
                                 <p> $900.00</p>
                              </td>
                              <td class=col4>
                                 <p> $900.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $600.00</p>
                              </td>
                              <td class=col4>
                                 <p> $600.00</p>
                              </td>
                              <td class=col4>
                                 <p> $600.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $490.00</p>
                              </td>
                              <td class=col4>
                                 <p> $534.00</p>
                              </td>
                              <td class=col4>
                                 <p> $534.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $48,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> $48,044.00</p>
                              </td>
                              <td class=col4>
                                 <p> $38,900.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $48,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> $48,044.00</p>
                              </td>
                              <td class=col4>
                                 <p> $38,900.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  --</p>
                  <p>Minimum college GPA (on a 4.0 scale):  2.5</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  2</p>
                  <p>Maximum credits/courses from a 2-year institution:  16</p>
                  <p>Maximum credits/courses from a 4-year institution:  20</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  12</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>Essay or Personal Statement </p>
                  <p>Statement of good standing from Prior Institution(s) </p>
                  <p>College Transcript(s) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  138</p>
                  <p>Transfers admitted percentage:  55.0%</p>
                  <p>Transfers admitted:  77</p>
                  <p>Transfers enrolled percentage:  26.0%</p>
                  <p>Transfers enrolled:  36</p>
                  <p>Students who applied for transfer from 2 year schools:  31.0%</p>
                  <p>Students who applied for transfer from 4 year schools:  69.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
                  <p>Junior </p>
                  <p>Senior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Orientation </p>
                  <p>Pre-admission transcript evaluation (determination of what courses will transfer) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>-- </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  Mar 1</p>
                  <p>Application fee:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $35,866.00</p>
                  <p>Room & Board(on-campus):  $10,144.00</p>
                  <p>Room & Board(off-campus):  $10,144.00</p>
                  <p>Additional estimated expenses:  $2,468.00</p>
                  <p>Costs per credit hour:  $1,500.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>International students eligible for need based aid </p>
                  <p>International students eligible for non-need based aid </p>
                  <p>Total Amount Awarded:  $791,225.00</p>
                  <p>Number of enrolled international undergraduates received aid:  48</p>
                  <p>Non-resident aliens must submit the following financial aid forms: </p>
                  <p>Foreign Student Certification of Finances </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  90</p>
                  <p>TOEFL (internet-based test) minimum score:  79</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Special International Student Orientation Program </p>
                  <p>International Student Adviser </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>