<body>

<table>
<tr>
   <td class="col2">
      

      
   </td>
<td class="col2 alignRight">

         <h1>Austin Peay State University</h1>
         <h2>Clarksville, TN</h2>
   </td>
</tr>
</table>

   <h1>At A Glance</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Main Address</h2>

            <div class="subTabSeperator"></div>
                  <p>601 College Street </p>
                  <p>Clarksville, TN 37044 </p>
                  <p>www.apsu.edu </p>
         </td>
         
         
         <td class="col2">
            <h2>Admission Office</h2>

            <div class="subTabSeperator"></div>
                  <p>PO Box 4548 </p>
                  <p>Clarksville, TN 37044-4548 </p>
                  <p>(931) 221-7661 </p>
                  <p>Fax : (931) 221-6168 </p>
                  <p>admissions@apsu.edu </p>
                  <p>Contact : Amy Deaton </p>
                  <p>Director of Admissions </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Type of School</h2>

            <div class="subTabSeperator"></div>
                  <p>Medium </p>
                  <p>Public </p>
                  <p>university </p>
                  <p>liberal arts college </p>
                  <p>4-year school </p>
                  <p>Coed </p>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>College Board Member </p>
                  <p>College Board Code: 1028 </p>
         </td>
         
         
         <td class="col2">
            <h2>Quick Facts</h2>

            <div class="subTabSeperator"></div>
                  <p>Regular Application Deadline : July 25 </p>
                  <p>Percentage of students graduating within 6 years : 37.0% </p>
                  <p>Total undergraduates : 9,735 </p>
                  <p>First-time degree-seeking freshmen : 1,522 </p>
                  <p>Average financial aid package : $10,397.00 </p>
                  <p>In-State Tuition : $7,158.00 </p>
                  <p>Out-of-State Tuition : $23,490.00 </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>School Calendar</h2>

            <div class="subTabSeperator"></div>
                  <p>Semester </p>
         </td>
         
         
         <td class="col2">
            <h2>Degree's Available</h2>

            <div class="subTabSeperator"></div>
                  <p>Associate </p>
                  <p>Bachelor's </p>
                  <p>Master's </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Setting</h2>

            <div class="subTabSeperator"></div>
                  <p>Small City (50-250k) </p>
                  <p>Urban </p>
                  <p>Commuter campus </p>
         </td>
         
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Deadlines</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission</h2>

            <div class="subTabSeperator"></div>
                  <p>Regular application due:   Jul 25</p>
                  <p>Priority application due :   --</p>
                  <p>College will notify student of admission :  --</p>
                  <p>Student must reply to acceptance by :   --</p>
                  <p>Housing deposit due :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning/ACT Score report due :   Aug 24</p>
                  <p>SAT subject score report due :   Aug 24</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Application due :   --</p>
                  <p>Financial Aid Priority Application due :   Feb 11</p>
                  <p>College will notify student :   --</p>
                  <p>Student must reply :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfer Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Transfer Application closing date :   Jul 25</p>
                  <p>College will notify student of transfer decision by :   --</p>
                  <p>Transfer priority application date :   --</p>
                  <p>Transfer student must reply :   --</p>
                  <p>Transfer deadline for filing financial aid forms :   --</p>
                  <p>Transfer priority financial aid deadline :   --</p>
                  <p>College will notify student of financial aid decisions on or about :   --</p>
                  <p>Student must reply to financial aid decision by :   --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall application due :   Aug 1</p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Major and Learning Environment</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Learning Environment</h2>

            <div class="subTabSeperator"></div>
                  <p>Calendar type :   Semester</p>
                  <p>Student-faculty ratio :   19 to 1</p>
                  <p>Degree's Offered in :   Associate, Bachelor's, Master's degrees</p>
                  <p>Graduating in 6 years :   37.0%</p>
                  <p>Returning for sophomore year :   67.0%</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Accreditation and Associations</h2>

            <div class="subTabSeperator"></div>
                  <p>Regionally Accredited </p>
                  <p>Southern Association of Colleges and Schools </p>
                  <p>College Board Member </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Most Popular Majors</h2>

            <div class="subTabSeperator"></div>
                  <p><b>Bachelor's</b><br/>  Business/Marketing : 19.0%<br/>Education : 10.0%<br/>Health Professions : 10.0%<br/>Communications/Journalism : 7.0%<br/>Liberal Arts : 6.0%<br/>Psychology : 5.0%<br/>Security and Protective Services : 5.0%<br/>Social Sciences : 5.0%<br/></p>
                  <p><b>Associates</b><br/>  Liberal Arts : 59.0%<br/>Engineering Technologies : 20.0%<br/>Business/Marketing : 14.0%<br/>Other : 7.0%<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>All Majors</h2>

            <div class="subTabSeperator"></div>
                  <p>Levels at which colleges offer undergraduate majors are designated by these letters : </p>
                  <p>A = Associate degree, B = Bachelor's degree, C = Certificate degree, D = Doctor degree, M = Master degree </p>
                  <p><b>Agriculture & Related Sciences</b><br/>  Agriculture, General B<br/></p>
                  <p><b>Biological & Biomedical Sciences</b><br/>  Biology/Biological Sciences, General B M<br/></p>
                  <p><b>Business, Management, Marketing, & Related Support</b><br/>  Business Administration and Management, General A M<br/>Business/Commerce, General B<br/>Non-Profit/Public/Organizational Management B<br/></p>
                  <p><b>Communication, Journalism & Related Programs</b><br/>  Mass Communication/ Media Studies B M<br/></p>
                  <p><b>Computer & Information Sciences, Support Services</b><br/>  Computer and Information Sciences, General B<br/></p>
                  <p><b>Education</b><br/>  Counselor Education/School Counseling and Guidance Services M<br/>Curriculum and Instruction M<br/>Education, General M<br/>Educational Leadership and Administration, General M<br/>Health Teacher Education B<br/>Reading Teacher Education M<br/>Special Education and Teaching, General B<br/></p>
                  <p><b>Engineering Technologies/Technicians</b><br/>  Engineering Technology, General B<br/></p>
                  <p><b>English Language, Literature & Letters</b><br/>  English Language and Literature, General B M<br/></p>
                  <p><b>Foreign Language, Literatures & Linguistics</b><br/>  Foreign Languages and Literatures, General B<br/>Spanish Language and Literature B<br/></p>
                  <p><b>Health Professions & Related Clinical Sciences</b><br/>  Clinical Laboratory Science/Medical Technology/Technologist B<br/>Medical Radiologic Technology/Science - Radiation Therapist B<br/>Nursing - Registered Nurse Training (RN, ASN, BSN, MSN) B<br/></p>
                  <p><b>History</b><br/>  History, General B<br/></p>
                  <p><b>Liberal Arts & Sciences, Gen Studies & Humanities</b><br/>  General Studies A B M<br/>Liberal Arts and Sciences/Liberal Studies B<br/></p>
                  <p><b>Mathematics & Statistics</b><br/>  Mathematics, General B<br/></p>
                  <p><b>Parks, Recreation & Fitness Studies</b><br/>  Health and Physical Education, General B M<br/></p>
                  <p><b>Philosophy & Religious Studies</b><br/>  Philosophy B<br/></p>
                  <p><b>Physical Sciences</b><br/>  Chemistry, General B<br/>Geology/Earth Science, General B<br/>Physics, General B<br/></p>
                  <p><b>Psychology</b><br/>  Psychology, General B M<br/></p>
                  <p><b>Public Administration & Social Services</b><br/>  Social Work B M<br/></p>
                  <p><b>Security & Protective Services</b><br/>  Criminal Justice/Law Enforcement Administration B<br/></p>
                  <p><b>Social Sciences</b><br/>  Political Science and Government, General B<br/>Sociology B<br/></p>
                  <p><b>Visual & Performing Arts</b><br/>  Art/Art Studies, General B<br/>Music, General B M<br/></p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Learning outside the classroom</h2>

            <div class="subTabSeperator"></div>
                  <p>Many colleges offer special programs like the opportunity to study abroad or participate in internships to get on-the-job training. Nearly all colleges provide extra academic help or tutoring to students who need it. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Cooperative Education </p>
                  <p>Double Major </p>
                  <p>Honors Program </p>
                  <p>Independent Study </p>
                  <p>Internships </p>
                  <p>Teacher Certification </p>
                  <p>Accelerated Program </p>
                  <p>Dual Enrollment of High School Students </p>
                  <p>English as a Second Language (ESL) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Off-Campus Study Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Study Abroad </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Available</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Army </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Extended Class Availability</h2>

            <div class="subTabSeperator"></div>
                  <p>Saturday Classes </p>
                  <p>Distance Learning </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Computer Services</h2>

            <div class="subTabSeperator"></div>
                  <p>825 Public computers, available in: Computer Center, Dorms, Libraries, Student Center </p>
                  <p>Dorms wired for access to campus-wide network </p>
                  <p>Dorms wired for high speed internet connections </p>
                  <p>Wireless network available </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>Campus Life</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>Campus General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Size :   Medium-sized</p>
                  <p>Unique Facilities :   observatory, art gallery</p>
                  <p>Geographic Location :   45 miles from Nashville.</p>
                  <p>Small City </p>
                  <p>Urban </p>
                  <p>Commuter Campus </p>
                  <p>Total undergraduates :   9,735</p>
                  <p>First-time degree-seeking freshmen :   1,522</p>
                  <p>Degree-seeking undergrads :   9,475</p>
                  <p>Graduate enrollment :   862</p>
         </td>
         
         
         <td class="col2">
            <h2>Student General Information</h2>

            <div class="subTabSeperator"></div>
                  <p>All students average age :   26</p>
                  <p>Full time students average age :   24</p>
                  <p>In state students :   89.0%</p>
                  <p>Out of  state students :   11.0%</p>
                  <p>Part Time students :   26.0%</p>
                  <p>Percentage of males :   40.0%</p>
                  <p>Percentage of females :   60.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Race/Ethnicity</h2>

            <div class="subTabSeperator"></div>
                  <p>Two or more races :   4.0%</p>
                  <p>Black African American :   19.0%</p>
                  <p>Asian :   2.0%</p>
                  <p>Hispanic/Latino :   5.0%</p>
                  <p>Race Ethnicity Unknown :   2.0%</p>
                  <p>White :   66.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Other Activities & Organizations</h2>

            <div class="subTabSeperator"></div>
                  <p>Other Activities & Organizations :   Alcohol not permitted on campus.</p>
                  <p>9.0% Men who Join Fraternities </p>
                  <p>9.0% Women who Join Sororities </p>
                  <p>Student Newspaper :   The All State</p>
                  <p>Student Newspaper URL :   http://www.theallstate.org</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Housing Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>First-year students living in college housing :   45.0%</p>
                  <p>All undergraduates living in college housing :   14.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Apartments For Married Students </p>
                  <p>Apartments For Single Students </p>
                  <p>Coed Housing </p>
                  <p>Fraternity/Sorority Housing </p>
                  <p>Men's Housing </p>
                  <p>Special Housing For Disabled Students </p>
                  <p>Women's Housing </p>
                  <p>Theme Housing </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional Housing Options</h2>

            <div class="subTabSeperator"></div>
                  <p>Housing deposit :   $200.00</p>
                  <p>Housing deposit is refundable in full if student does not enroll. </p>
                  <p>Car is allowed for freshman </p>
                  <p>Pet is not allowed in the Dorm </p>
         </td>
         
         
         <td class="col2">
            <h2>General Athletics</h2>

            <div class="subTabSeperator"></div>
                  <p>Team Name :   Governors</p>
                  <p>Sport Member :   NCAA</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Sport's Levels Available</h2>

            <div class="subTabSeperator"></div>
                  <p>NCAA Division I </p>
                  <p>NCAA Division IAA </p>
                  <p>Intercollegiate </p>
                  <p>Intramural </p>
                  <p>Scholarship </p>
         </td>
         
         
         <td class="col2">
            <h2>Counseling And Wellness</h2>

            <div class="subTabSeperator"></div>
                  <p>Career counseling </p>
                  <p>Employment services for undergraduates </p>
                  <p>Financial aid counseling </p>
                  <p>Health services </p>
                  <p>On-campus daycare </p>
                  <p>Personal counseling </p>
                  <p>Adult (re-entering) student services/programs </p>
                  <p>Veteran's counselor </p>
                  <p>Alcohol/substance abuse counseling </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Services for Students with Disabilities</h2>

            <div class="subTabSeperator"></div>
                  <p>Services and/or facilities for hearing impaired </p>
                  <p>Partial services for students with learning disabilities </p>
                  <p>Services and/or facilities for speech or communications disorders </p>
                  <p>Services and/or facilities for visually impaired </p>
                  <p>Wheelchair Accessibility </p>
         </td>
         
         
         <td class="col2">
            <h2>Academic Support Services</h2>

            <div class="subTabSeperator"></div>
                  <p>Learning center </p>
                  <p>Study skills assistance </p>
                  <p>Tutoring </p>
                  <p>Writing center </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Activities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Activity Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Available on Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Y indicates available and N indicates not available</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Campus Ministries</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Choral Groups</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Concert Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Dance Activity</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Drama/Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Film Society</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Fraternities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Government or Political Activity </p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>International Student Organization</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Jazz Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Literary Magazine</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Marching Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Model United Nations</p>
                     </td>
                        <td class=col2>
                              <p> N</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Music Ensembles</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Musical Theater</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Opera</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Pep Band</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Radio Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Sororities</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Student Newspaper</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Symphony Orchestra</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Television Station</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Yearbook</p>
                     </td>
                        <td class=col2>
                              <p> Y</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>Sports</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Sport Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Levels Available</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Baseball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Men's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Basketball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Men's NCAA Division I</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Cross-Country</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's NCAA Division I</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Men's NCAA Division IAA</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Football(non-tackle)</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Golf</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's NCAA Division I</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Racquetball</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Rifle</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Soccer</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Softball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Table tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Tennis</p>
                     </td>
                        <td class=col2>
                              <p> Men's Intercollegiate</p>
                              <p> Women's Intercollegiate</p>
                              <p> Men's Scholarship</p>
                              <p> Women's Scholarship</p>
                              <p> Men's NCAA Division I</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track and Field</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Indoor</p>
                     </td>
                        <td class=col2>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Track: Outdoor</p>
                     </td>
                        <td class=col2>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>Volleyball</p>
                     </td>
                        <td class=col2>
                              <p> Women's Intercollegiate</p>
                              <p> Women's Scholarship</p>
                              <p> Men's Intramural</p>
                              <p> Women's Intramural</p>
                              <p> Women's NCAA Division I</p>
                        </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Applying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="col2">
            <h2>General Applying Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Application Fee:   $15.00</p>
                  <p>Application fee notes:   Paper/Online</p>
                  <p>Total applicants :   3,453</p>
                  <p>Admitted :   2,959</p>
                  <p>Enrolled :   1,522</p>
                  <p>Less selective 86.0% of applicants admitted </p>
                  <p>Applied early admission :   --</p>
                  <p>Admitted early admission :   --</p>
                  <p>Applied early action :   --</p>
                  <p>Admitted early action :   --</p>
                  <p><br/><br/>Admission stats are based on first-time, degree seeking freshmen from Fall 2012. </p>
         </td>
         
         
         <td class="col2">
            <h2>Very Important</h2>

            <div class="subTabSeperator"></div>
                  <p>Academic GPA </p>
                  <p>Standardized Test Scores </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Considered</h2>

            <div class="subTabSeperator"></div>
                  <p>Rigor of secondary school record </p>
         </td>
         
         
         <td class="col2">
            <h2>Test Policies for Admission Decisions</h2>

            <div class="subTabSeperator"></div>
                  <p>Required: SAT or ACT </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Test Policies for placement</h2>

            <div class="subTabSeperator"></div>
                  <p>SAT Reasoning Test </p>
                  <p>ACT </p>
                  <p>AP </p>
                  <p>CLEP </p>
         </td>
         
         
         <td class="col2">
            <h2>SAT score use policy</h2>

            <div class="subTabSeperator"></div>
                  <p>Highest Section Scores Across Test Dates  </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Additional requirements for home-schooled students</h2>

            <div class="subTabSeperator"></div>
                  <p>Special requirements for home-schooled applicants: </p>
                  <p>(in addition to any polices listed) </p>
                  <p>Transcript/record of courses and grades </p>
         </td>
         
         
         <td class="col2">
            <h2>Other Test Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>ACT/SAT not required of active duty military. </p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>A note from the college</h2>

            <div class="subTabSeperator"></div>
                  <p>Rigor of secondary school record, GPA, and test scores very important. </p>
         </td>
         
         
         <td class="col2">
            <h2>High school class rank of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>Top Tenth :   13.0%</p>
                  <p>Top Quarter :   34.0%</p>
                  <p>Top Half :   70.0%</p>
                  <p>Bottom Half :   30.0%</p>
                  <p>Bottom Quarter :   9.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>GPAs of incoming freshmen</h2>

            <div class="subTabSeperator"></div>
                  <p>3.75+ :   16.0%</p>
                  <p>3.5 - 3.74 :   14.0%</p>
                  <p>3.25 - 3.49 :   17.0%</p>
                  <p>3.00 - 3.24 :   18.0%</p>
                  <p>2.50 - 2.99 :   23.0%</p>
                  <p>2.00 - 2.49 :   10.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>SAT Critical Reading</h2>

            <div class="subTabSeperator"></div>
                  <p>600 - 699 :   15.0%</p>
                  <p>500 - 599 :   34.0%</p>
                  <p>400 - 499 :   40.0%</p>
                  <p>300 - 399 :   11.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>SAT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>600 - 699 :   13.0%</p>
                  <p>500 - 599 :   38.0%</p>
                  <p>400 - 499 :   34.0%</p>
                  <p>300 - 399 :   15.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT Composite </h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   3.0%</p>
                  <p>24 - 29 :   25.0%</p>
                  <p>18 - 23 :   62.0%</p>
                  <p>12 - 17 :   10.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>ACT Math</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   1.0%</p>
                  <p>24 - 29 :   21.0%</p>
                  <p>18 - 23 :   44.0%</p>
                  <p>12 - 17 :   34.0%</p>
         </td>
         
         
         <td class="col2">
            <h2>ACT English</h2>

            <div class="subTabSeperator"></div>
                  <p>30 - 36 :   8.0%</p>
                  <p>24 - 29 :   25.0%</p>
                  <p>18 - 23 :   51.0%</p>
                  <p>12 - 17 :   16.0%</p>
         </td>
         </tr>
         <tr>
         <td class="col2">
            <h2>Advanced Placement Program (AP) Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Offers credit for AP Exams : Yes </p>
                  <p>Offers placement into higher-level courses for AP Exams : Yes </p>
                  <p>From the college: The total amount of credit earned by a non-traditional method, including correspondence and extension credit, which is acceptable to apply toward a degree is limited to one-half the total number of credits required for the degree sought. </p>
         </td>
         
   <!-- display tables-->

         <table>
            <tbody>
            <h2>High school Coursework</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Course Name</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Recommended</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>High School diploma required, GED accepted</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Visual/Performing Arts</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>History</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English</p>
                     </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Math</p>
                     </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science</p>
                     </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Science Lab</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Studies</p>
                     </td>
                              <td class=col3>
                                 <p> 1</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Foreign Language</p>
                     </td>
                              <td class=col3>
                                 <p> 2</p>
                              </td>
                              <td class=col3>
                                 <p> 0</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>TEST Scores</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col2>
                        <h2>Test Subjects</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col2>
                        <h2>Middle 50% of First-Year Students</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                  <p>Percent who submitted SAT scores : 3.0% and Percent who submitted ACT scores : 89.0%</p>
            </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Critical Reading</p>
                     </td>
                        <td class=col2>
                              <p> 430 - 540</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>SAT Math</p>
                     </td>
                        <td class=col2>
                              <p> 430 - 560</p>
                        </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col2>
                        <p>ACT Composite</p>
                     </td>
                        <td class=col2>
                              <p> 19 - 24</p>
                        </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>AP & Admission Policy</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Min Score Required</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Number of Credits</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Equivalent Course(s)</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Art History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ART 1030</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Biology</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> BIOL 1010 & 1011   </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus AB</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 5</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 1910 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Calculus BC</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 10</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 1910, 1920    </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Chemistry</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> CHEM 1010 & 1011, or 1110 & 1111</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> CHEMCHEM 1010, 1022, 1020, 1020 or CHEM 1110, 1111, 1120, 1121</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science A</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> CSCI 1010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Computer Science AB</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> CSCI 1010 & 2010  </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Language and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 1010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>English Literature and Composition</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> ENGL 1010, 1020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>European History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 1220</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 1010, 1020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>French Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> FREN 1010, 1020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>German Language and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> GERM 1010, 1020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 11</p>
                              </td>
                              <td class=col4>
                                 <p> LATIN 1010, 1020, 2010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Latin Literature</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> LATIN 1010, 1020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ECON 2010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> ECON 2010, 2020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Aural Subscore</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1185 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1185 & 1195</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Non-Aural Subscore</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 1</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1185 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 2</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1185 & 1195</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Music Theory</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1180</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> MUS 1180, 1190</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics B</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2010 & 2020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Electricity and Magnetism</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2110 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2110 & 2120</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Physics C: Mechanics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2110 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> PHYS 2110 & 2120</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Psychology</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> PSY 1010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Language</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 1010, 1020 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Spanish Literature and Culture</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 8</p>
                              </td>
                              <td class=col4>
                                 <p> SPAN 1010, 1020 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Statistics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> MATH 1530</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: 2-D Design Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ART 1010 </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Studio Art: Drawing Portfolio</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> ART 1040    </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States Government and Politics</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> POLS 2010   </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>United States History</p>
                     </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 2010</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p> </p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 6</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 2010 & 2020</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>World History</p>
                     </td>
                              <td class=col4>
                                 <p> 4</p>
                              </td>
                              <td class=col4>
                                 <p> 3</p>
                              </td>
                              <td class=col4>
                                 <p> HIST 1220</p>
                              </td>
                  </tr>
            </tbody>
         </table>

         <table>
            <tbody>
            <h2>College-Level Examination Program (CLEP)</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Exam</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Minimum Grade for Credit</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Credit Hours Awarded</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Algebra</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Government</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American History II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>American Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Analysis and Interpretation of Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Business Law, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Calculus with Elementary Functions</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Educational Psychology, Introduction To</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Composition</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Compostion with Essay</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>English Literature</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>French - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 8</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Biology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>General Chemistry</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 8</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>German - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 8</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Human Growth and Development</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Humanities</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Information Systems and Computer Applications</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Macroeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Mathematics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Microeconomics</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Natural Science</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Pre-calculus</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 4</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Management</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Principles of Marketing</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Psychology</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Social Sciences and History</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 6</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Sociology, Introductory</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Spanish - Second Semester</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 8</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization I</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Western Civilization II</p>
                     </td>
                              <td class=col3>
                                 <p> 50</p>
                              </td>
                              <td class=col3>
                                 <p> 3</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>Paying</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Financial Aid Distribution & Stats</h2>

            <div class="subTabSeperator"></div>
                  <p>% of scholarship / grants :   52.0%</p>
                  <p>% of loans / jobs :   48.0%</p>
                  <p>% Applied for need-based aid :   92.0%</p>
                  <p>% Judged to have need :   88.0%</p>
                  <p>Average 1st year financial aid package :   $10,397.00</p>
                  <p>Avg non need-based aid :  $4,512.00</p>
                  <p>Avg need-based scholarship or grant award :  $7,108.00</p>
                  <p>Avg need-based loan :  $3,094.00</p>
                  <p>Avg indebtedness at graduation :   $26,181.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Deadlines</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial Aid Priority Deadline :  Feb 11</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Contact Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Financial aid contact name :  Donna Price</p>
                  <p>Financial aid office phone :  (931) 221-7907</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Forms</h2>

            <div class="subTabSeperator"></div>
                  <p>Domestic first-year financial aid applicants must submit the following forms, if applicable: </p>
                  <p>FAFSA </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Part-Time Costs</h2>

            <div class="subTabSeperator"></div>
                  <p>Cost per credit hour (in-state):  $233.00</p>
                  <p>Cost per credit hour (out-of-state):  $837.00</p>
                  <p>Note:   These costs are tuition fees only. In some cases, fees and other expenses can be additional.</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid Policies</h2>

            <div class="subTabSeperator"></div>
                  <p>This school practices need-blind admissions. </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Non need-based financial aid determined by</h2>

            <div class="subTabSeperator"></div>
                  <p>Academics </p>
                  <p>Art </p>
                  <p>Athletics </p>
                  <p>Leadership </p>
                  <p>Music/Drama </p>
                  <p>ROTC </p>
                  <p>State/District Residency </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Work Study Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>Nights </p>
                  <p>For part-time students </p>
                  <p>Weekends </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tuition payment plans</h2>

            <div class="subTabSeperator"></div>
                  <p>Credit card payment </p>
                  <p>Deferred payment </p>
                  <p>Installment payment </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>ROTC Programs</h2>

            <div class="subTabSeperator"></div>
                  <p>ROTC, Air Force : Offered at a cooperating institution </p>
                  <p>ROTC, Army : Offered on Campus </p>
         </td>
         </tr>
   <!-- display tables-->

         <table>
            <tbody>
            <h2>Annual College Costs </h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col4>
                        <h2>Cost Category</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>On Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>Off Campus</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col4>
                        <h2>At Home</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>In-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,158.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,158.00</p>
                              </td>
                              <td class=col4>
                                 <p> $7,158.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Out-of-state tuition and fees:</p>
                     </td>
                              <td class=col4>
                                 <p> $23,490.00</p>
                              </td>
                              <td class=col4>
                                 <p> $23,490.00</p>
                              </td>
                              <td class=col4>
                                 <p> $23,490.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Room and board:</p>
                     </td>
                              <td class=col4>
                                 <p> $7,774.00</p>
                              </td>
                              <td class=col4>
                                 <p> $8,549.00</p>
                              </td>
                              <td class=col4>
                                 <p> $3,274.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Books and supplies:</p>
                     </td>
                              <td class=col4>
                                 <p> $1,550.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,550.00</p>
                              </td>
                              <td class=col4>
                                 <p> $1,550.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated personal expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $2,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> $2,000.00</p>
                              </td>
                              <td class=col4>
                                 <p> $2,000.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Transportation expenses:</p>
                     </td>
                              <td class=col4>
                                 <p> $2,538.00</p>
                              </td>
                              <td class=col4>
                                 <p> $2,538.00</p>
                              </td>
                              <td class=col4>
                                 <p> $2,538.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total In-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $21,020.00</p>
                              </td>
                              <td class=col4>
                                 <p> $21,795.00</p>
                              </td>
                              <td class=col4>
                                 <p> $16,520.00</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col4>
                        <p>Estimated Total Out-of-state:</p>
                     </td>
                              <td class=col4>
                                 <p> $37,352.00</p>
                              </td>
                              <td class=col4>
                                 <p> $38,127.00</p>
                              </td>
                              <td class=col4>
                                 <p> $32,852.00</p>
                              </td>
                  </tr>
            </tbody>
         </table>
            <p>The prices listed above are probably not what you and your family will pay. Most college students receive financial aid, which reduces the amount the family actually pays. For U.S. colleges, use the college's net price calculator to get the best estimate of what your family will pay.</p>

         <table>
            <tbody>
            <h2>Athletic Scholarship Opportunities</h2>

            <div class="mainTabSeperator"></div>
            <tr>
                     <td class=col3>
                        <h2>Sport</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Male</h2>

                        <div class="subTabSeperator"></div>
                     </td>
                     <td class=col3>
                        <h2>Female</h2>

                        <div class="subTabSeperator"></div>
                     </td>
            </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Baseball</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Basketball</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Cross-Country</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Football</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Golf</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Soccer</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Softball</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Tennis</p>
                     </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Track and Field</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
                  <tr class="borderBottom">
                     <td class=col3>
                        <p>Volleyball</p>
                     </td>
                              <td class=col3>
                                 <p> </p>
                              </td>
                              <td class=col3>
                                 <p> Available</p>
                              </td>
                  </tr>
            </tbody>
         </table>
   </tbody>
   </table>
   <h1>For Transfer Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Credit Information</h2>

            <div class="subTabSeperator"></div>
                  <p>Minimum number of credits:  12</p>
                  <p>Minimum college GPA (on a 4.0 scale):  --</p>
                  <p>Lowest grade earned for course that may be transferred for credit (on a 4.0 scale):  1</p>
                  <p>Maximum credits/courses from a 2-year institution:  --</p>
                  <p>Maximum credits/courses from a 4-year institution:  --</p>
                  <p>Minimum credits transfers must complete to earn bachelor's degree:  30</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Admission Requirements (Required)</h2>

            <div class="subTabSeperator"></div>
                  <p>College Transcript(s) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Students who applied for transfer</h2>

            <div class="subTabSeperator"></div>
                  <p>Total students who applied for transfer:  1,399</p>
                  <p>Transfers admitted percentage:  93.0%</p>
                  <p>Transfers admitted:  1,306</p>
                  <p>Transfers enrolled percentage:  62.0%</p>
                  <p>Transfers enrolled:  878</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Terms in which transfer students may enroll</h2>

            <div class="subTabSeperator"></div>
                  <p>Fall </p>
                  <p>Spring </p>
                  <p>Summer </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Transfers accepted as</h2>

            <div class="subTabSeperator"></div>
                  <p>1st semester freshman </p>
                  <p>2nd semester freshman </p>
                  <p>Sophomore </p>
                  <p>Junior </p>
                  <p>Senior </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for students transferring IN from another school</h2>

            <div class="subTabSeperator"></div>
                  <p>Advisor </p>
                  <p>Orientation </p>
                  <p>Pre-admission transcript evaluation (determination of what courses will transfer) </p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Special Requirements</h2>

            <div class="subTabSeperator"></div>
                  <p>-- </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
   <h1>For International Students</h1>

   <div class="mainTabSeperator"></div>
      <table>
      <tbody>
         <tr>
         <td class="">
            <h2>Admission for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>International Application Due for Fall 2014:  Aug 1</p>
                  <p>Application fee:  $15.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Annual College Costs </h2>

            <div class="subTabSeperator"></div>
                  <p>Tuition and Fees:  $23,490.00</p>
                  <p>Room & Board(on-campus):  $7,774.00</p>
                  <p>Room & Board(off-campus):  $8,549.00</p>
                  <p>Additional estimated expenses:  --</p>
                  <p>Costs per credit hour:  $837.00</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Financial Aid</h2>

            <div class="subTabSeperator"></div>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Tests for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>TOEFL Required of non-resident alien applicants </p>
                  <p>TOEFL (internet-based test) average score:  --</p>
                  <p>TOEFL (internet-based test) minimum score:  61</p>
                  <p>TOEFL (paper) average score:  --</p>
                  <p>TOEFL (paper) minimum score:  --</p>
         </td>
         </tr>
         <tr>
         <td class="">
            <h2>Services for International Students</h2>

            <div class="subTabSeperator"></div>
                  <p>English as a Second Language Program On Campus for International Students </p>
                  <p>International Student Adviser </p>
                  <p>Special International Student Orientation Program </p>
         </td>
         </tr>
   <!-- display tables-->
   </tbody>
   </table>
<script type="text/javascript" src="https://common.collegeboard.org/webanalytics/js/web_analytics_footer.js"></script>
</body>